var powerThoughts = [
"Se você quer alcançar a grandeza, pare de pedir permissão. ~Anônimo",
"As coisas funcionam melhor para aqueles que fazem o melhor de como as coisas funcionam. ~John Wooden",
"Para viver uma vida criativa, devemos perder o medo de estar errado. ~Anônimo",
"Se você não está disposto a arriscar o usual, terá que se contentar com o comum. ~Jim Rohn",
"Confie porque você está disposto a aceitar o risco, não porque é seguro ou certo. ~Anônimo",
"Todos os nossos sonhos podem se tornar realidade se tivermos coragem de persegui-los. ~Walt Disney",
"Coisas boas vêm para as pessoas que esperam, mas coisas melhores vêm para aqueles que saem e as pegam. ~Anônimo",
"Se você fizer o que sempre fez, obterá o que sempre obteve. ~Anônimo",
"O sucesso é caminhar de fracasso em fracasso sem perder o entusiasmo. ~Winston Churchill",
"Apenas quando a lagarta pensou que o mundo estava acabando, ela se transformou em borboleta. ~Provérbio",
"Empreendedores de sucesso são doadores e não receptores de energia positiva. ~Anônimo",
"Sempre que você vê uma pessoa de sucesso, você só vê as glórias públicas, nunca os sacrifícios privados para alcançá-las. ~Vaibhav Shah",
"As oportunidades não acontecem, você as cria. ~Chris Grosser",
"Tente não se tornar uma pessoa de sucesso, mas tente se tornar uma pessoa de valor. ~Albert Einstein",
"Grandes mentes discutem ideias; mentes medianas discutem eventos; mentes pequenas discutem pessoas. ~Eleanor Roosevelt",
"Eu não falhei. Acabei de encontrar 10.000 maneiras que não funcionam. ~Thomas A. Edison",
"Se você não valoriza seu tempo, os outros também não. Pare de dar seu tempo e talentos - comece a cobrar por isso. ~Kim Garst",
"Um homem de sucesso é aquele que pode estabelecer uma base firme com os tijolos que outros jogaram nele. ~David Brinkley",
"Ninguém pode fazer você se sentir inferior sem o seu consentimento. ~Eleanor Roosevelt",
"Todo o segredo de uma vida bem-sucedida é descobrir qual é o destino de alguém fazer e depois fazê-lo. ~Henry Ford",
"Se você está passando pelo inferno, continue. ~Winston Churchill",
"Aqueles que são loucos o suficiente para pensar que podem mudar o mundo, são os que o fazem. ~Steve Jobs",
"Não levante a voz, melhore seu argumento. ~Anônimo",
"O que nos parece provações amargas são muitas vezes bênçãos disfarçadas. ~ Oscar Wilde",
"O sentido da vida é encontrar o seu dom. O propósito da vida é dá-lo. ~Anônimo",
"A distância entre insanidade e genialidade é medida apenas pelo sucesso. ~Bruce Feirstein",
"Quando você para de perseguir as coisas erradas, você dá às coisas certas uma chance de te pegar. ~Lolly Daskal",
"Não tenha medo de desistir do bom em busca do ótimo. ~John D. Rockefeller",
"Nenhuma obra-prima foi criada por um artista preguiçoso.~ Anônimo",
"Se você não consegue explicar de forma simples, você não entende bem o suficiente. ~Albert Einstein",
"Bem-aventurados aqueles que podem dar sem lembrar e receber sem esquecer. ~Anônimo",
"Faça uma coisa todos os dias que te assusta. ~Anônimo",
"Qual é o sentido de estar vivo se você não tenta pelo menos fazer algo notável. ~Anônimo",
"A vida não é sobre encontrar a si mesmo. A vida é sobre criar a si mesmo. ~Lolly Daskal",
"Nada no mundo é mais comum do que pessoas mal sucedidas com talento. ~Anônimo",
"Conhecimento é estar ciente do que você pode fazer. Sabedoria é saber quando não fazer. ~Anônimo",
"Seu problema não é o problema. Sua reação é o problema. ~Anônimo",
"Você pode fazer qualquer coisa, mas não tudo. ~Anônimo",
"A inovação distingue entre um líder e um seguidor. ~Steve Jobs",
"O pensamento deve se tornar seu ativo capital, não importa os altos e baixos que você encontre em sua vida. ~Dr. APJ Kalam",
"Eu acho que quanto mais eu trabalho, mais sorte eu pareço ter. ~Thomas Jefferson",
"O ponto de partida de toda conquista é o desejo. ~Napolean Hill",
"O sucesso é a soma de pequenos esforços, repetidos dia após dia. ~Robert Collier",
"Se você quer alcançar a excelência, você pode chegar lá hoje. A partir deste segundo, pare de fazer um trabalho menos que excelente. ~Thomas J. Watson",
"Todo o progresso ocorre fora da zona de conforto. ~Michael John Bobak",
"Você só pode ter sucesso se desejar ter sucesso; você só pode falhar se não se importar em falhar. ~Philippos",
"Coragem é resistência ao medo, domínio do medo - não ausência do medo. ~Mark Twain",
"Apenas deixe para amanhã o que você está disposto a morrer deixando de fazer. ~Pablo Picasso",
"As pessoas costumam dizer que a motivação não dura. Bem, nem o banho - é por isso que o recomendamos diariamente. ~Zig Ziglar",
"Nós nos tornamos o que pensamos a maior parte do tempo, e esse é o segredo mais estranho. ~Earl Nightingale",
"O único lugar onde o sucesso vem antes do trabalho é no dicionário. ~Vidal Sassoon",
"A melhor razão para começar uma organização é fazer sentido; criar um produto ou serviço para tornar o mundo um lugar melhor. ~Guy Kawasaki",
"Eu acho que quando você tem um interesse real na vida e uma vida curiosa, o sono não é a coisa mais importante. ~Martha Stewart",
"Não é o que você olha que importa, é o que você vê. ~Anônimo",
"O caminho para o sucesso e o caminho para o fracasso são quase exatamente os mesmos. ~Colin R. Davis",
"A função da liderança é produzir mais líderes, não mais seguidores. ~Ralph Nader",
"Sucesso é gostar de si mesmo, gostar do que você faz e gostar de como você faz. ~Maya Angelou",
"À medida que olhamos para o próximo século, os líderes serão aqueles que capacitam os outros. ~Bill Gates",
"Um verdadeiro empreendedor é alguém que não tem uma rede de segurança por baixo de si. ~Henry Kravis",
"O primeiro passo para o sucesso é dado quando você se recusa a ser cativo do ambiente em que se encontra pela primeira vez. ~Mark Caine",
"Quando eu ouso ser poderoso - usar minha força a serviço da minha visão, então se torna cada vez menos importante se eu tenho medo. ~Audre Lorde",
"Sempre que você se encontra do lado da maioria, é hora de parar e refletir. ~Mark Twain",
"O guerreiro de sucesso é o homem comum, com foco de laser. ~Bruce Lee",
"Desenvolva o sucesso dos fracassos. O desânimo e o fracasso são dois dos degraus mais seguros para o sucesso. ~Dale Carnegie",
"Se você não desenhar seu próprio plano de vida, é provável que você caia no plano de outra pessoa. E adivinhe o que eles planejaram para você? Não muito. ~ Jim Rohn",
"Se você realmente quer algo, não espere por isso - ensine-se a ser impaciente. ~Gurbaksh Chahal",
"Não deixe que o medo de perder seja maior do que a emoção de ganhar. ~Robert Kiyosaki",
"Se você quer fazer uma mudança permanente, pare de focar no tamanho dos seus problemas e comece a focar no tamanho de você! ~T. Harv Eker",
"Pessoas bem sucedidas fazem o que as pessoas mal sucedidas não estão dispostas a fazer. Não deseje que fosse mais fácil, gostaria que você fosse melhor. ~Jim Rohn",
"A razão número um pela qual as pessoas falham na vida é porque elas ouvem seus amigos, familiares e vizinhos. ~Napoleon Hill",
"Na minha experiência, há apenas uma motivação, que é o desejo. Nenhuma razão ou princípio o contém ou se opõe a ele. ~Jane Smiley",
"O sucesso não consiste em nunca cometer erros, mas em nunca cometer o mesmo uma segunda vez. ~George Bernard Shaw",
"Eu não quero chegar ao fim da minha vida e descobrir que vivi apenas o comprimento dela. Eu quero ter vivido a largura dela também. ~Diane Ackerman",
"Você deve esperar grandes coisas de si mesmo antes de poder fazê-las. ~Michael Jordan",
"Motivação é o que faz você começar. Hábito é o que faz você continuar. ~Jim Ryun",
"As pessoas raramente têm sucesso a menos que se divirtam no que estão fazendo. ~Dale Carnegie",
"Não há nenhuma chance, nenhum destino, nenhum destino, que possa impedir ou controlar a firme determinação de uma alma determinada. ~Ella Wheeler Wilcox",
"Nosso maior medo não deve ser o fracasso, mas o sucesso em coisas da vida que realmente não importam. ~Francis Chan",
"Você precisa acordar todas as manhãs com determinação se quiser ir para a cama com satisfação. ~George Lorimer",
"Para ter sucesso você deve aceitar todos os desafios que surgirem no seu caminho. Você não pode simplesmente aceitar os que você gosta. ~Mike Gafka",
"Sucesso é... conhecer seu propósito na vida, crescer para alcançar seu potencial máximo e plantar sementes que beneficiem os outros. ~ John C. Maxwell",
"Seja miserável. Ou motive-se. O que quer que tenha que ser feito, é sempre sua escolha. ~Wayne Dyer",
"Para realizar grandes coisas, devemos não apenas agir, mas também sonhar, não apenas planejar, mas também acreditar.~ Anatole France",
"A maioria das coisas importantes do mundo foram realizadas por pessoas que continuaram tentando quando parecia não haver nenhuma ajuda. ~Dale Carnegie",
"Você mede o tamanho da conquista pelos obstáculos que teve que superar para alcançar seus objetivos. ~Booker T. Washington",
"Dificuldades reais podem ser superadas; são apenas as imaginárias que são invencíveis. ~Theodore N. Vail",
"É melhor falhar na originalidade do que ter sucesso na imitação. ~Herman Melville",
"A sorte fica do lado de quem ousa. ~Virgil",
"As pequenas mentes são domadas e subjugadas pelo infortúnio; mas as grandes mentes se elevam acima dele. ~Washington Irving",
"O fracasso é o condimento que dá sabor ao sucesso. ~Truman Capote",
"Não deixe que o que você não pode fazer interfira no que você pode fazer. ~John R. Wooden",
"Você pode ter que lutar uma batalha mais de uma vez para vencê-la. ~Margaret Thatcher",
"Fique com fome, fique tolo. ~Steve Jobs",
"Faça ou morra. ~Mahatama Gandhi",
"Seja a mudança que você quer ver no mundo. ~Mahatama Gandhi",
"A Challenger tinha sistema de segurança projetado pelo Windows",
"A Inteligência artificial nao funciona por causa da Burrice Natural.",
"A Kaiser dá dor de cabeca... ninguém pode negar!",
"A bebida mata lentamente! E daí? Nao estou com pressa...",
"A beleza nao esta apenas nas curvas, esta tambem nas vias de acesso.",
"A cal é virgem porque o pincel é brocha!",
"A carne näo aumentou, o boi é que diminuiu.",
"A chance dessa tag ser selecionada era de uma em 1040!",
"A clara do ovo e o açúcar, no forno, suspiravam...",
"A coisa mais profunda em certas mulheres é o sono!",
"A esperança e a sogra sao sempre as últimas a morrer...",
"A esperança é a última que morre.... MAS MORRE!!!",
"A felicidade de cada Calouro está na morte de cada Veterano!!!",
"A felicidade se constrói a partir das pequenas coisas feitas com amor.",
"A fita é virgem porque o gravador é stéreo",
"A fortuna faz amigos. A desgraça prova se eles existem de fato.",
"A história se repete porque ninguém presta atençao.",
"A ignorancia é temporária, a estupidez nao.",
"A imaginaçao é mais importante que o conhecimento...",
"A informaçäo mais necessária é sempre a menos disponível.",
"A ligaçäo caiu. Será que ela se machucou muito ??",
"A mata é virgem porque o vento é fresco",
"A melhor defesa contra lógica é estupidez.",
"A mente, como os pára-quedas, só funcionam quando abertas.",
"A modéstia morreu quando a falsa modéstia nasceu.",
"A modéstia é uma das minhas inúmeras virtudes...",
"A mulher chora antes do casamento; o homem depois.",
"A mulher do vizinho é sempre mais magra que a nossa...",
"A namorada disse para o namorado: Olha o guarda, guarda!",
"A namorada disse para o namorado: Olha o tira, tira!",
"A pior coisa da censura é .",
"A pior coisa do sexo oral é a vista...",
"A pomba é o passarinho da Paz, e a mulher a paz do passarinho !",
"A primeira amnésia a gente nunca esquece !",
"A proteçao anti-bomba do World Trade Center era feita por Windows",
"A sensaçao é boa, mas a posiçao é ridícula!",
"A sensibilidade de um homem está na força do seu punho.",
"A tagline da mensagem anterior é ridicula.",
"A tcla do mu tclado stá com um pquno problminha...",
"A teimosia é a força de vontade do chato.",
"A terra está 98% cheia. Delete quem voce puder.",
"A verdade é fruto do tempo, e nao da autoridade...",
"A vida começa aos 14.4K",
"A vida nao é um conto de fadas, mas um conto de fatos...",
"A vida se vive para frente, mas se entende para trás.",
"A vida é imprevisível... Coma a sobremesa antes!",
"A vida é uma doença sexualmente transmissível.",
"A vingança tarda mais näo falha!!!",
"A virgindade é curável, se detectada cedo!",
"A véia Quacker, a avó do mingau...",
"A última palavra é sempre da mulher: SIM SENHOR !!!",
"A: nao encontrado... B: nao encontrado... formatando C:...",
"ABISMADO: Pessoa que sofreu queda em abismo",
"AMOR: 4 letras de felicidade... ADEUS: 5 letras que choram...",
"ATENCAO: Feche a DOOR quando sair! Ass: Sysop.",
"ATENÇAO, todos dados do disco rígido serao apagados. Continua (S/S)?",
"ATROPELADO: Nú Artístico",
"AVISO! É proibido por lei remover esta tagline!",
"Abandone as esperanças aquele que posta mensagens aqui.",
"Abandone as esperanças aquele que teclar --+ aqui.",
"Abismo? Que abiiiiiiiiiiiiiiiiiiiiiiiiiisssssssssssmmo...",
"Acelere seu XT: 9.8 m/s²",
"Acentua&@o % um problema que j$ foi superado.",
"Acha seu 286 lento? Volte a usar um TK!",
"Acho qUe miNHa TEclA CaPS loCk eSta COm dEfeIto...",
"Acho que penso, logo acho que existo...",
"Acho que vou fazer umas Tag's hoje...",
"Achoqueaminhabarradeespaçosestácomdefeito...",
"Aconteça o que acontecer, näo babe no teclado!",
"Acredita em reencarnaçäo? Me dê U$5000 e te pago na próxima",
"Adao foi sortudo mesmo... nao tinha sogra nem irmao...",
"Adoro XT! Detesto 486... é muito rápido...",
"Adäo desesperado dizia: Näo fui eu! Näo fui eu!",
"Adäo disse a Eva: Eu tenho, você näo tem!!!",
"Adäo foi sortudo mesmo. Näo tinha sogra e nem irmäo!",
"Agir sem pensar é como atirar sem mirar.",
"Agora säo 23:53. Você sabe onde seu modem está?",
"Agua mole em pedra dura, tanto bate... até que molha!",
"Ahá, agora você vem cuspir no prato que te comeu...",
"Ajoelhou, tem que dar reply !",
"Algumas curas säo piores do que a doença.",
"Alguns dias säo täo lindos que é um crime sair da cama.",
"Alguns espelhos deveriam pensar duas vezes antes de refletir algo.",
"Ama teu próximo! Ainda mais se for uma loira de olhos azuis!",
"Amador: O mesmo que masoquista",
"Amante é o namorado que leva pijama...",
"Amazonas: Indivíduo apaixonado por áreas de baixo meretrício",
"Amigo a gente escolhe, parente a gente tolera.",
"Amigo: Alguém que tem os mesmos inimigos que você.",
"Amigos chegam e se vao, inimigos se acumulam.",
"Amizades as vezes nao se conservam em álcool.",
"Amor -- uma grave doença mental. - Platäo",
"Anatomia é destino!",
"Anciäo é multado por passar dos 80.",
"Antarctica... Uma paixao nacional como a mulher dos outros",
"Antes de ser martelo lembre-se que tb já foi prego.",
"Antes eu nao era perfeito, faltava-me a modéstia...",
"Antes à tarde do que nunca...",
"Antigas tradiçöes tem a força de uma lei.",
"Antigos espíritos do mau, tranformem essa forma decadente em MUNRRAH",
"Apaguei meu arquivo de TAG, e agora ?",
"Aquela baiana vive de renda: é rendeira.",
"Aquela tag é VERDADEIRA ->   <- Aquela tag é FALSA.",
"Aquele que nunca admite ser criança, jamais será adulto!",
"Aqueles que bebem para esquecer, geralmente esquecem de pagar a conta.",
"Aqueles que bebem pra esquecer. Favor pagar adiantado.",
"Aquilo ali é uma ratazana? (primeira vez que vi um scanner de mao)",
"Armando Nascimento de Jesus, vulgo presépio...",
"Armarinho: Vento proveniente do mar",
"Armas nao matam pessoas..., EU AS MATO!",
"Artesäo: Que aparenta estar muito excitado",
"As 7 maravilhas do mundo na verdade sao 2, mulher e pizza!",
"As caras vemos, os coraçöes nao sabemos.",
"As coisas podem piorar, voce é que näo tem imaginaçäo...",
"As esferas sao os alicerces do homem .",
"As facas GYNSU 2000 säo capazes de cortar as meias Vivarina?",
"As melhores coisas da vida säo grátis. Caro é o motel.",
"Atençao, o vírus de bruço costuma atacar nas noites de sexta a domingo!",
"Atençäo pra essa TAGline........... Obrigado pela atençäo",
"Atençäo! Näo molhe nem exponha essa tagline ao calor.",
"Atençäo, o vírus de bruço costuma atacar nas noites de sexta a domingo!",
"Atençäo: Mensagem proibida para menores de 14400 bps!",
"Atirou no proprio estomago para matar a fome.",
"Atlantida tinha um sistema de flutuaçao controlado pelo Windows.",
"Até um completo imbecil entende essa TAG. Voce entendeu?",
"Até um imbecil passa por inteligente se ficar calado...",
"Até um leao tem que proteger-se contra moscas...",
"Audaciosamente escrevendo o que ninguem jamais escreveu!!",
"BASIC é como varíola, a gente pega quando é criança.",
"BBS Mania - A alegria da Telesp, Telerj, Telemig...",
"BBS:O melhor metodo para triplicar sua conta telefonica!",
"BBS? Ah, sim... BUSINESS BOARD SYSTEM!",
"BEBIDA MATA LENTAMENTE !!! E dai, eu näo estou com pressa",
"BIOS = Bicho Ignorante Operando o Sistema",
"BIOS: Bicho Ignorante Operando o Sistema...",
"Back in the USSR - música dos Beatles, por John Lenin e Ringo Stalin.",
"Backup nao encontrado: (A)bortar, (R)epetir, (P)ânico?",
"Backup not found: (Q)uem mandou usar o Stacker?",
"Barcos pequenos devem se manter próximos à praia.",
"Barganhar: Receber um botequim como herança",
"Barracäo: Proibir a entrada de cachorro",
"Barulhento por fora, vazio por dentro.",
"Bassê: 1/2 cachorro de algura e 1 1/2 de comprimento.",
"Bebadho, eu? Hic! Eu echtou chobrio... Hic! Hic! Hic!",
"Beleza multiplicada por inteligência é igual a uma constante.",
"Beleza nao é fundamental, já dizia Esperidiao Amin...",
"Bicha brasileira só pensa em mae e Nova Iorque...",
"Bicha é igual carbono, faz ligaçäo para todos os lados.",
"Bill Gates esta rico. Peter Norton tambem. Porque continuo pobre??!",
"Bill Gates tornou-se um Deus. Windows é praga divina.",
"Bingo no Iraque: B-52..F-16..A-10.. F-18..F-117..B-2",
"Biscoito: Relaçäo sexual repetida",
"BlueWave 6.66  : DEMO version...",
"Bom que é bom joga BUCK ROGERS em um AT486DX....",
"Bonita camisa-de-força, Fernandinho...",
"Boy nao erra porque errar é humano...",
"Boy que e boy, nao vira a fita, capota o carro...",
"Boy que é boy nao vira a fita, capota o carro...",
"Bumba meu boi: Bovino invadindo a fábrica de fogos",
"Buááááá... Minhas taglines acabaram... chuif!",
"Bígamo: Um homem que cometeu o mesmo erro duas vezes.",
"CD \ROM... Dá acesso direto à BIOS...",
"CHEGA! Nunca mais posto mensagens! Vou é ver a novela das 8!!!",
"CHUCHU: o quarto estado físico da água.",
"Cabeça grande, cérebro pequeno.",
"Cada civilizaçao cria seu Deus, que deixa de existir junto com ela...",
"Cada mania tem seu doido de estimaçao.",
"Cada pessoa atinge os céus de sua própria forma.",
"Cada vez sobra mais mês no fim do dinheiro",
"Caiu na rede é terminal!",
"Casal feliz: Marido surdo e mulher cega.",
"Casamento, um romance no qual o herói morre no primeiro capítulo.",
"Casar é a melhor maneira de se arrumar uma empregada.",
"Cazuza escolhia suas parceiras pelo Windows.",
"Cem mil lemmings näo podem estar errados.",
"Cerveja faz mal... quando falta!",
"Chato é aquele q vc fala:aparece lá em casa e ele aparece",
"Chato: Uma pessoa que fala quando deveria estar ouvindo.",
"Chernobyl usava o Windows para monitorar os reatores.",
"Chicote: Pessoa chamada Francisco e de pequena estatura",
"Chip, é impossível comer um só... é horrível!",
"Claro que nao perdi a memória... tenho o back-up guardado em disquete.",
"Clavícula: Clave muito pequena",
"Coagir: Agir em equipe",
"Coaxar: Achar em conjunto com outros",
"Coloque o cinto-de-segurança. Vou tentar algo novo.",
"Com o patrocinio da URBS a RBT vai mudar de nome: RVT",
"Comer até adoecer, beber até sarar!",
"Como dizia Jack, o estripador: Vamos por partes...",
"Como escapar de vampiros? É só envenenar seu sangue...",
"Como se acentua palavras em código morse¿",
"Como sentar 4 gaúchos num banquinho: Vire-o de ponta cabeça",
"Complô? Näo. Näo complei näo.",
"Computadores nunca vao substituir a estupidez humana.",
"Computadores näo cometem erros, pessoas tolas sim.",
"Comunguei: Manter relaçöes sexuais com homossexual",
"Conceiçäo: Elemento de soma. Ex.: quatro com seis säo dez",
"Conhecimento auxilia por fora, mas só o amor socorre por dentro.",
"Conheça o Brasil, mas a passagem para Miami é mais barata...",
"Consórcio de nove meses da Cegonhex, adquira sua cota já....",
"Conta Telefônica ! Você ainda vai se assustar com ela !",
"Continua a operacao? [S]im [N]ao [T]alvez [J]amais [N]unca",
"Continue a ser como é!Os analistas precisam sobreviver !",
"Coraçao de macho nao bate. Dá porrada!",
"Coraçäo de cara macho mesmo näo bate. Dá porrada.",
"Cotonete Tagline: ¦¦¦¦==============¦¦¦¦",
"Coxa e Atlético sao controlados pelo Windows.",
"Crianças precisam mais de exemplos do que de críticas.",
"Crime nao compensa... entao meu emprego é um crime?",
"Criminoso: Alguém que foi pego.",
"Cruzeiro Real, aquele que nao vale (realmente) nada...",
"Cuidado com as imitaçoes. Sexo só existem dois!",
"Cuidado com o telível vilus do Cebolinha...",
"Cuidado com os caes que ladram e mordem!",
"Cuidado! Piratas de taglines à vista! P->",
"Cérbero, o cäo de duas cabeças. O único que ladra enquanto morde.",
"Cágado: O mesmo que bôrrado",
"Círculo vicioso é um gordo oferecendo cigarros.",
"DOS 6.0? To fora!",
"Da primeira vez näo funcionou ? Destrua as evidencias de que tentou !",
"Davi Adao de Nascimento ama a Eva Camacho... os opostos se atraem!",
"De 2400 em 2400 o usuário enche o HD!",
"De onde mais se espera é que nao sai nada mesmo...",
"De um sabäo p/ outro: Eu te OMO mas teu sorriso MINERVA.",
"Deixe-me ver sua licença de caça de TAGS.",
"Depauperado: Que foi operado de fimose",
"Depois de uma mensagem vem sempre uma tagline...",
"Depois do carro(ça) popular, vem aí o XT popular!",
"Depois que se envolveu com cocaina, ele tá fazendo carreira solo",
"Desabrochar: Uma dezena de homens com problema de impotência",
"Desdentada: O mesmo que dez mordidas",
"Desta vez votem nas putas, porque os FILHOS delas nao resolvem nada !",
"Desviado: Uma dezena de homossexuais",
"Detergente: Ato de prender indivíduos suspeitos",
"Deus criou o Homem antes da mulher para nao ouvir palpite.",
"Deus disse: E = 1/2mv² - Ze²/r e apareceu a luz...",
"Deus fez o mundo em seis dias,no sétimo foi aberta uma CPI contra ele.",
"Deus nos deus os amendoins, mas nós é que temos que quebrá-los",
"Deus te proteja e o Diabo que te carregue.",
"Deus é amor... Amor é cego... Ray Charles é Deus!",
"Deus é brasileiro... nasceu em Gov. Valadares e mudou-se para Miami...",
"Deus é brasileiro: nasceu em Valadares e mudou p/ Miami.",
"Deus é real, a nao ser que seja declarado como integer...",
"Deus é real.  Pensando bem... pode ser integer, Boolean, Char, etc..",
"Deutsche Welle: vela em alemao...",
"Diga nao à pirataria, se você já tiver o programa...",
"Diga-me que computador tens e dir-te-ei quem és...",
"Digitacao : ato ou efeito de digitar; Digitar : realizar digitacao",
"Dinheiro nao traz felicidade. Dê-me o seu e viva feliz!",
"Documentado: Pessoa que tem como hábito passar menta no ânus",
"Dois homens traídos pela mesma mulher tornam-se meio parentes.",
"Dorme filhinho, senao vem um vírus e te apaga da memória!",
"Dorme, filhinho, senäo um vírus vem e te come.",
"DoubleSpace: Duplicador de dores de cabeça",
"Doutor, nao preciso mais usar óculos? Nao. Agora só bengala e cachorro",
"Drogas, tô fora! Saí pra comprar mais, volto já...",
"Drogas? Pra que? Já tenho um XT...",
"Dura Lex, sed Latex! (A lei é dura, mas estica!)",
"Dê emoçäo a sua vida: faca pipocas com a panela aberta !",
"E a mula disse: é o cumulo!!!",
"E o padeiro falou para o John Lennon: O sonho acabou",
"ESGOTADO: Pessoa que caiu no esgoto",
"ESTAµ TAGLINE FO¯I FE§ITA AT{RAVÉS DO WINDOëWS",
"Economize! Use só HS-LINK e use o papel higienico dos dois lados!",
"Edifício: Antônimo de é fácil",
"Educaçäo começa em casa, e geralmente termina onde começa.",
"Egoísta é quem pensa mais em si mesmo do que em mim...",
"Ei Fred, a Wilma perdeu um pacote de msg....oba IABADABADÜÜÜÜ...",
"Ei gata, existe 1/2 para te levar para 1/4 ?  Sim, ý ...",
"Ei! Tá olhando o que? A mensagem já acabou! Aperta ENTER logo!",
"Ei!!!! Desligue esta droga, e vá dormir !!",
"Ela só usa hexa? Que 61658! Além de 65050 ela é muito 12237514!!!",
"Ela é tao perua que mandou retocar seus raios X...",
"Elas usam Sempre Livre... Eu uso Modems.",
"Elefantes e mulheres nunca se esquecem.",
"Em Deus nós confiamos. O resto, pague em dinheiro.",
"Em Londres, lavar o óculos com sabonete sempre melhora o tempo.",
"Em Portugal os restaurantes fecham para almoco...",
"Em boca fechada näo entra mosca.... nem sai!  bzzzzzzz!",
"Em cada 10 pessoas, 6 sabem contar. As outras 3 sao ignorantes.",
"Em matéria de Rede, prefiro aquela feita no Ceará...",
"Em matéria de redes, prefiro aquelas fabricadas no Ceará...",
"Em terra de cego que tem um olho dá o fora!",
"Em terra de olho, quem tem cego... errei!",
"Emagreça 10 quilos por mês sem fazer força... pegue AIDS",
"Encurralar: Esfolar o ânus",
"Entrar pra dentro e sair pra fora é pleorgasmo...",
"Entre todas as 35 alternativas, sair correndo é a melhor.",
"Entre todas as pessoas que conheci, vc certamente é uma delas.",
"Entreguei: Cercado por homossexuais",
"Entäo,o monstro acertou o ataque e... perai,vou precisar de mais dados",
"Envelhecer näo é täo ruim, se considerarmos a alternativa...",
"Epaminondas que joga dadinho na praça andou de caiaque e bateu no céu!",
"Errar é humano! Persistir no erro, mais humano ainda!",
"Errar é humano, disse o pato saindo de cima da galinha.",
"Errar é humano, persistir no erro é burrice...",
"Erro ao acessar a FAT. Tento acessar a magrela? (Y/N)",
"Erro no sistema.Pressione F13 para continuar.",
"Escova: Lugar onde näo säo mais enterrados cadaveres...",
"Escrever sobre arte é como dançar sobre arquitetura.",
"Esfera: Animal selvagem já domesticado",
"Esgotado: Pessoa que caiu no esgoto...",
"Esperto: O mesmo que distante",
"Essa mensagem é uma corrente... Copie-a e envie-a para 10 amigos...",
"Esta TAG é uma corrente. Tire 10 cópias e distribua aos amigos.",
"Esta noite nao vai dar querida... tenho um modem!",
"Estou economizando TAGS para uma ocasiao especial....",
"Estouro: Bovino que sofreu operaçäo de mudança de sexo",
"Estudo é a luz da vida. Economize energia...",
"Estupidez nao é desculpa por nao pensar...",
"Estupradores nada mais sao que ginecologistas frustrados...",
"Está morto! Podemos elogiá-lo à vontade...",
"Eu acreditava no sistema, até que formataram minha família...",
"Eu adoro meus amigos, suas irmäs, mais ainda!",
"Eu amo o windows. Ele é que näo me ama.",
"Eu apenas as roubo. Quer explicaçäo, consulte um filósofo.",
"Eu cnsigo diigtar 400 caractreres pro minuo1!!",
"Eu costumava ler livros. Agora só leio arquivos .TU1",
"Eu decorei o Aurélio inteiro! Só näo consigo me lembrar...",
"Eu estou em forma ... redondo é uma forma, näo?",
"Eu indeciso? Nao tenho certeza.",
"Eu nao sou baixinho. Minha sombra é que é pequena!",
"Eu nao sou ninguém. Ninguém é perfeito. Logo, eu sou perfeito.",
"Eu nao sou um animal! Eu sou ... bem, nao sou um animal.",
"Eu näo perdi a cabeça... Deve haver um backup em algum lugar.",
"Eu näo posso ser estúpido. Já completei o 2º grau!",
"Eu näo sou baixinho. Minha sombra é que é pequena !",
"Eu pertenço à NBA (National Bebum s Association) e ao Drink Team!",
"Eu posso ser estúpido, Mas meu consolo é que vc é mais...",
"Eu quase nada sei, mas desconfio de muita coisa...",
"Eu queria que Adäo tivesse morrido com todas as suas costelas.",
"Eu sou mais humilde que voce!",
"Eu sou täo inocente quanto um ovo recém-botado.",
"Eu sou um computador... computadores nunca cometem herros!",
"Eu só escrevi, nao me peça para entender!",
"Eu teria sofrido muito mais se tivesse entendido...",
"Eu tive um pesadelo... DIR C:... 0 bytes livres",
"Eu tive um pesadelo...DIR C:...00000000000000000015786 bytes free",
"Eu tive um sonho... DIR C:... 965875434567865367890 bytes livres",
"Evite a ressaca, mantenha-se bêbado!!!",
"Evite as drogas... Desligue a TV no domingo!",
"Evite confisco do seu dinheiro: Gaste tudo!",
"Evite estupros, diga sim!",
"Evite uma vida sedentária: Beba água!",
"Evite ver um idiota todos os dias. Quebre o espelho.",
"Excesso nunca é o suficiente.",
"Extensäo: Pessoa muito tranquila",
"Extra! Jogadores de tênis promovem nova onda de saques",
"Extra!Extra! Usuario suicida se joga do Windows.. Extra!",
"F13 para continuar...",
"FIAT = Fui Idiota Agora é Tarde",
"Faca um brasileiro trabalhar, mande-o para o Japao...",
"Faculdade de Engenharia é como mae, uma só! Duas ninguém aguenta!",
"Faculdade. Você ainda vai abandonar uma!",
"Falar alto näo melhor seu argumento.",
"Fax Terrier: Copiadora de cachorros de longa distancia",
"Faz quase dois anos que nao falo com minha sogra... ela nao dá chance!",
"Faça os olhos de uma loira brilharem. Acenda uma lanterna na orelha dela!",
"Faça qualquer besteira, desde que com entusiasmo...",
"Faça seu candidato trabalhar; Näo vote nele.",
"Faça uma loira sorrir no sábado! Conte uma piada na quinta.",
"Feel good. Traduçäo: Bom fio",
"Feia por fora, bonita por dentro?   Vira do avesso!",
"Fico no micro o dia inteiro. Nao tenho amigos. Mas AMIGA eu tenho!",
"Fiz os 13 pontos e nao estou feliz. 7 na loteria e 6 na cabeça...",
"Flash-Modem, O Modem Mais Rápido do Mundo... comprem!",
"Fluxograma: Direçäo em que cresce o capim",
"Frases de efeito: O phaser do vizinho é sempre mais verde.",
"Freud é o pai da psicanálise. Quem é a mae?",
"Fuja! Ele tem uma GINSU SWORD e uma VIVARINA'S Ring Mail !",
"Fusck(a) you.",
"Fusível: Aquilo que pode ser transformado em fuzil",
"GO AHEAD: Gol de cabeca.",
"Garotas, ao lerem essa tagline considerem-se CANTADAS!",
"Garotos sao garotos, e alguns homens também.",
"Garçom, cancela a pizza e traga outra, por favor.",
"Garçon, me traz um X-Pao e um suco d'água.",
"Gatos: prova de que comer e dormir nao é de todo ruim.",
"Gay é como jabuticaba:Nasce graudado no pau!",
"Gay é como jacaré: Se defende com o rabo",
"Gay é como juiz de direito:Vai de vara em vara",
"Genitalia é uma linha aérea Italiana???",
"Gere fractais em seu monitor: Aproxime um ímä da tela.",
"Gincana: Gim com cachaça",
"Glande: Sinônimo de (enolme)",
"Glosar: Atingir o (olgasmo)",
"Gosto nao se discute... se critica!",
"Grande Mestre, só te liguei pra te dar um (alo).",
"Gêmeo tenta se suicidar e mata o irmäo por engano!",
"HOMOGENIO: Sabäo em pó usado pelo Aladin",
"Ha 10 anos atrás - cara comprei meu XT, agora só falta o modem de 300",
"HaHaHaHaHaHaHaHaHaHaHaHa, meus olhos estao cheios de lagrimas",
"Hackers INC: Vem pra LISTA NEGRA voce tambem ...",
"Halogênio: Forma de cumprimentar uma pessoa muito inteligente",
"Herrar é umano, percisti no herro é burriçe...",
"Hey man. Traduçäo: Amém!",
"Hiroshima tinha proteçao nuclear controlada pelo Windows.",
"Homem de sucesso:aquele que ganha mais que sua",
"Homem desmunhecando e mulher pisando duro nao enganam nem no escuro!",
"Homem que é homem nao toma o mel, come a abelha!",
"Homossexual: Sabäo para lavar as partes íntimas",
"Há males que vem para pior...",
"Há mulheres que säo como estradas: tem curvas perigosas.",
"Há mulheres que só sao fiéis à moda...",
"I don t care. Traduçäo: Eu näo quero",
"Ignorância é temporária. Estupidez é eterna.",
"Imaginaçao é mais importante que conhecimento...",
"Imagine uma linha imaginária.",
"Individualistas: Unidos!",
"Inicializar: ATZ - Discar: ATD - Finalizar: ATlogo",
"Insert New Disk for Drive C: Press ENTER when ready.",
"Intimaçäo: O mesmo que carícias íntimas",
"Intuiçao feminina:  resultado de milhares de anos sem pensar.",
"Inté, o processador rurar !!! 33 megaré.",
"Itamar? Carma, ainda vai ficar pior, uai...",
"Ja que a aula é um dever, vamos dever mais uma aula.",
"Jamais bata em um homem com óculos, use as maos...",
"Jeca Tatu tinha um computador com EIA I/O.",
"Jesus Cristo é a resposta. Agora, qual é sua pergunta?",
"Jogo adventures, jogo RPGs, jogo a sogra na parede...",
"Jogos via modem: a melhor diversäo. Pra Telepar!",
"Jovem, ao completar 18 anos anos, vá até boate mais próxima e comemore",
"Juiz de Fora expulsou Sao Bernardo do Campo...",
"Já afogo minhas máguas há tanto tempo que elas já sabem nadar...",
"Já experimentou tentar colocar a pasta de dente de volta no tubo?",
"Já näo se fazem mais espíritos esportivos como antigamente...",
"Já que a aula é um dever, vamos dever mais uma aula...",
"Já que a primeira impressao é a que fica, use uma impressora laser!",
"Júri: Um grupo escolhido para decidir quem tem o melhor advogado.",
"LAPTOPspirose: vírus transmitido pela urina do mouse",
"LOCAL ECHO = TERMINAL GAGO.",
"Ladräo que rouba ladräo... Tem taglines de montäo!",
"Laptospirose: Doença provocada pela urina do mouse...",
"Lavar a honra com sangue suja a roupa toda!",
"Lei do universitário: Nunca deixe seu professor notar que você existe.",
"Leiläo: Mulher chamada Leila com mais de 2 metros de altura",
"Lembre-se os fins justificam os meios.",
"Lembre-se, onde quer que você vá, lá estará.",
"Leve o dinheiro, o carro, e a TV, mas deixe meu micro!",
"MULHER.EXE... ótimo programa, mas veio sem manual...",
"Macho que é macho nao engole sapos... come as pererecas!",
"Macho que é macho nao reparte o cabelo, racha a testa!!",
"Macho que é macho näo come mel, mastiga abelha",
"Macho que é macho näo engole sapos. Come as pererecas!!",
"Macho que é macho näo estaciona, puxa a calçada!",
"Macho que é macho usa Stacker e nao faz back-up...",
"Macho que é macho, nao estaciona. Puxa o meio-fio.",
"Mais vale um na mäo do que dois no sutiä.",
"Mamae me mandou ser bonzinho. Mas ela já se enganou antes.",
"Mamäe! Eu näo quero visitar o vovô! Quieto, filho, e continua cavando!",
"Manda mais tags pra mim!! Estou ficando sem...",
"Mandioca e sogra ! As boas estäo debaixo da terra...",
"Manhêêê, se Deus é amor e o amor é cego, entao o Stevie Wonder é Deus?",
"Mantenha sua CPU virgem, nao remova o HIMEM.",
"Mas é claro que Deus existo!",
"Masoquista que é masoquista joga Wing Commander em XT.",
"Masoquista que é masoquista programa assembler com COPY CON",
"Masoquista: -Me bate! Me bate!    Sádico: - Näo!!!",
"Masoquista: 486 com CGA e Windows",
"Mau humor: Chutei o cachorro, bati na mulher e dei ALT-H no BBS",
"Maçaneta: Maçä muito pequena",
"Melhor duas abelhas voando do que uma na mäo.",
"Melhor entender pouco do que nao entender muito.",
"Memoria RAM  - Raramente Atende ao Micreiro",
"Memoria RAM ou memoria de Rä ?",
"Menstruaçao é ruim, mas o pior é quando ela nao vem...",
"Mentes, como pára-quedas, só funcionam quando abertos.",
"Mesmo um cachorro sem nariz sente o cheiro de um filé.",
"Mestre... Sim gafanhoto... Algum dia vou poder jogar Kung Fu no micro?",
"Mestruaçäo é ruim, mas o pior é quando ela näo vem...",
"Meu HD tem 100k de bad sector e 10M de bad-windows",
"Meu PC näo tem RAM, tem perereca!",
"Meu Whinchester é garanhäo... Sempre HARDdisk...",
"Meu modem está de greve: Só conecta a 2400!",
"Meu médico: Sinto, cabelo e inteligência näo cabem na mesma cabeça.",
"Meu outro micro é um TK-82C !!!",
"Meus desejos, para mim, säo ordens.",
"a vida tem a cor que vc pinta",
"Viva cada dia como se fosse o último, um dia você acerta",
"Minha avó morreu aos 115 anos... no parto!",
"Minhoca é um absurdo. Näo tem pé nem cabeça!",
"Ministério: Aparelho de som de tamanho reduzido",
"Modem 2400, uma beleza de carroça.",
"Modem de portugues trabalha a CANECAS e näo a BAUDS",
"Modens de 2400 bps favor usar a pista da direita.",
"Modens de 2400 favor trafegar no acostamento.",
"Movimento contra taglines imbecis; Mande contribuiçöes para:",
"Muito para o leste já é oeste...",
"Muitos beijam a mao que gostariam de cortar.",
"Muitos recebem conselhos. Só os sábios tiram proveito.",
"Muitos seriam covardes se tivessem coragem o suficiente.",
"Mulher = Geladeira! Näo precisa olhar pra saber se esta lá!",
"Mulher de 50 anos quem gosta é Pitanguy!",
"Mulher de amigo meu pra mim é homem. Só como por trás.",
"Mulher de amigo meu é homem, mas nao confio no meu lado feminino...",
"Mulher feia aqui, bate e volta...",
"Mulher feia e urubu, comigo é na pedrada...",
"Mulher feia é igual a macaco gordo, só quebra galho..",
"Mulher nao tem cérebro; tem adubo p/ crescer cabelo ...",
"Mulher nao tira Carteira de Habilitacao... Tira porte de arma!",
"Mulher é igual carne. Quanto mais se bate, mais macia fica.",
"Mulher é igual chiclete, quanto mais se pisa, mais gruda no pé!",
"Mulher é igual chicletes, quanto mais mexe mais dá bola",
"Mulher é que nem Chips: impossivel comer uma só!",
"Mulher é que nem filme, só se revela no escuro !!!",
"Mulher é sólida. Se fosse líquida, eu beberia.",
"Mulher é tudo igual: so muda o endereco !",
"Murphy baseou toda sua pesquisa no Windows",
"Mäe que consente engorda uma serpente.",
"NOKU. O refrigerante japones! Tome NOKU voce tambem! Hai!",
"Na guerra dos sexos, ambos os lados dormem sempre com o inimigo.",
"Na natureza nada se cria, nada se perde, tudo se formata...",
"Nada mais me impressiona. Já fui a todas as festas!",
"Nada mais raro do que um bom traseiro nas inglesas...",
"Nada é tao inevitável quanto um erro que você prevê...",
"Nada é tao simples que nao possa ser avacalhado!",
"Nada é täo ruim que näo possa piorar...",
"Nada é täo simples que näo possa ser avacalhado.",
"Namorada Grávida:(A)borta, (R)econhece ou (F)oge?",
"Nao adianta afogar as mágoas, elas já aprenderam a nadar!",
"Nao adianta.. a fila ao lado sempre é mais rapida!",
"Nao bebo e nao fumo, mas às vezes minto...",
"Nao bebo mais. Nem menos, assim ta bom.",
"Nao confunda a CPU do PC com a CPI do PC...",
"Nao cuspa pra cima, pois pode cair no seu rosto...",
"Nao existe mulher feia, você é que bebeu pouco...",
"Nao existem mulheres frígidas, apenas mal esquentadas.",
"Nao funcionou da primeira vez? Desista de pular de pára-quedas...",
"Nao importa para onde você vá... é sempre morro acima e contra o vento.",
"Nao mato aulas... elas é que me matam!",
"Nao me faça perguntas e nao precisarei mentir.",
"Nao responder também é uma resposta.",
"Nao se ama duas vezes a mesma mulher...",
"Nao se odeie logo pela manha, durma até meio-dia...",
"Nao se pode confiar nas mulheres, uma delas pode estar sendo sincera...",
"Nao sou jovem o suficiente para saber tudo!",
"Nao sou um animal! Sou hmmmmm... bem, nao sou um animal.",
"Nao tem porquê ser pessimista. Nao vai funcionar mesmo...",
"Nao tente ser täo afiado. Vai acabar se cortando.",
"Napoleao organizou sua tática em Waterloo pelo Windows.",
"Napoleao só perdeu uma batalha: a ultima.",
"Nasceu chorando, viveu reclamando, e morreu desapontado.",
"Nasci careca, pelado e sem dente. O que vier é lucro!",
"Nenhuma generalizaçäo é totalmente certa, nem mesmo essa.",
"Nessa msg foram consumidas 2 doses de vodka...",
"Neurose... já basta a minha!",
"New User: -O que é LOGOFF? +++ATH0... NO CARRIER",
"Newton morreu. Einstein morreu. E nao me sinto muito bem...",
"Ninguém acredita em um mentiroso mesmo que esteja falando a verdade.",
"Ninguém atira no Papai Noel.",
"Ninguém entra,ninguém sai, até minha tag roubada aparecer!",
"Ninguém testa a profundidade de um rio com ambos os pés.",
"Ninguém é constante, a nao ser que esteja morto.",
"No Brasil, lei é como vacina. Umas pegam, outras näo.",
"No dia do meu aniversário mando um telegrama de parabéns a meus pais...",
"No fim tudo dá certo! Se ainda nao deu... ainda nao chegou o fim!",
"No fim tudo dá certo, se ainda näo deu certo, ainda näo chegou o fim!!",
"No fundo... sou bastante superficial.",
"No natal do Bill Gates nao tem perú. Só WIN-Chester...",
"No verbo computar, só eu levo desvantagem...",
"Nossa, caiu uma aleluia dentro do meu café!?!",
"Nossa, por um momento o que voce disse pareceu fazer sentido...",
"Novo comando Format: DBLSPACE [ENTER]...",
"Num Xo Casado, Xo Xoteiro.",
"Numa coisa homens e mulheres concordam: ambos nao confiam em mulheres!",
"Nunca aceite um drinque de um urologista.",
"Nunca como com o estômago vazio...",
"Nunca concorde comigo, isso abala minha auto-confiança...",
"Nunca confie em ninguém que fala bem de todos.",
"Nunca confie em um cozinheiro magrela.",
"Nunca deixe o computador saber que você está com pressa!",
"Nunca empreste dinheiro a amigos. Causa AMNESIA!",
"Nunca subestime o poder da estupidez humana.",
"Nunca tive problemas com droga. Só com a policia...",
"Nuvens? Afague-as. Chuvas? Acaricie-as. Ventos? Alisios.",
"Näo adianta balancar...o ultimo pingo sempre é na cueca.",
"Näo adianta.. a fila ao lado SEMPRE é mais rapida!",
"Näo bebo e näo fumo, mas às vezes minto...",
"Näo bebo mais. Nem menos, assim tá bom.",
"Näo brinque com fogo. Ele é chato, näo sabe brincar.",
"Näo copie minhas taglines!",
"Näo ensine porcos a cantar. Voce perde seu tempo e incomoda o porco.",
"Näo existe mulher feia, voce é que bebeu pouco...",
"Näo existe nada que CTRL-ALT-DEL näo resolva!",
"Näo fique chateado, 1200 seria pior...",
"Näo importa para onde você vai: é sempre morro acima e contra o vento.",
"Näo mato aulas; elas é que me matam ...",
"Näo roube, o governo odeia concorrência",
"Näo saber é ruim, mas nao querer saber é pior.",
"Näo só defendo as massas como as devoro.",
"Näo tenho o manual mas näo sou pirata, sou autodidata.",
"Näo transmita a 2400. Vá ditando que é mais rápido!",
"Näo é a LEE que tem bolso pequeno. E você que usa 51/4.",
"Näo é da conta de ninguém, nem da minha.",
"Näo é um bug, é um feature.",
"O Alceni Guerra disse: Papai Noel, esqueça a minha Caloi!!!.",
"O Amâncio Pinto e seu irmao H. Romeu Pinto adoram o Clodovil...",
"O Bateau Mouche foi projetado utilizando o Windows",
"O Brasil está em nossas mäos e näo adianta lavar.",
"O Fusca do vizinho e sempre mais bonito do que o seu LADA!",
"O Guru Cebola disse: A BBSmania pode levar a gravidez!",
"O Iraque usava o Windows para controlar a mira dos SCUD s.",
"O Machado de Assis, afiado pelo Lima Duarte, Castrô Alves...",
"O Ministerio da Saude adverte: Injetar tag's é prejudicial a saúde.",
"O Ministério da Saúde Adverte: Mulher descontente é prejudicial !!!",
"O Monitor CGA do vizinho é sempre mais verde.",
"O Passos Dias Aguiar casou com a Guiomar... os opostos se atraem!",
"O Spock só usa camisinhas vulcanizadas...",
"O Universo por nós conhecido é apenas uma versao beta...",
"O Windows controlava o sist. de segurança do trem pagador.",
"O Windows nao é ruim, é só esperar ele ficar pronto...",
"O Windows nao é um vírus... vírus costumam fazer alguma coisa...",
"O Windows näo é a tal de praga dos 7 discos que a BIBLIA.DOC cita?",
"O Windows näo é ruim, voce que usa virado do avesso...",
"O Windows näo é ruim, é só esperar ele ficar pronto...",
"O Zeppelin usava o Windows para previnir vazamentos de gás.",
"O amor platônico é aquele do pescoço para cima.",
"O amor pode ser cego, mas nao é burro!",
"O amor sempre aparece quando esperamos o inesperado.",
"O amor tudo pode, exceto contra a pobreza e dor de dente.",
"O amor é a ilusao de que uma mulher é diferente das outras...",
"O apressado come cru... mas nao morre de fome!",
"O beijo tambem é cultura, quanto mais se beija, mais se conhece língua",
"O casamento é o principal motivo do divórcio.",
"O casco do TITANIC foi projetado pelo Windows.",
"O chato näo é ser chato, o chato é ficar sem ter quem chatear...",
"O chefe saiu: (T)etris, (P)rince of Persia, (F)1-GP",
"O cinto de castidade da EVA foi projetado pelo Windows",
"O colete à prova de balas de Getúlio foi feito pelo Windows.",
"O computador nao tem memória, só uma breve lembrança.",
"O cúmulo do racismo: pedir whisky black and white em copos separados!",
"O difícil näo é dormir tarde, é acordar cedo.",
"O direito de ser ouvido näo significa direito de ser levado a sério.",
"O fogäo tinha seis bocas, mas näo foi a Roma.",
"O fígado faz mal à bebida...",
"O governador do Paraná é paranóico!",
"O helicóptero do Ulysses era controlado pelo Windows.",
"O historiador é um profeta ao contrário...",
"O homem ama POUCO frequentemente. A mulher MUITO raramente.",
"O homem conhece a vida cedo demais, a mulher tarde demais.",
"O homem nao e ainda mais doido porque nao tem duas maes.",
"O impossível nós fazemos... Milagre? Demora um pouco mais...",
"O ladräo acredita que todos roubam.",
"O lixeiro passou e levou o Windows por engano...",
"O maior castigo para um bígamo? Duas sogras!",
"O mais dificil em Tróia foi embrulhar o cavalo...",
"O manual é o melhor amigo das dúvidas...",
"O melhor amigo do homem as vezes é um cachorro!",
"O melhor computador que existe é o meu, porque é o que eu tenho...",
"O melhor movimento feminista continua sendo o dos quadris...",
"O meu computador é indecente, ele computa!!!",
"O monitor CGA do vizinho é sempre mais verde...",
"O passado nao perdoa... mas o presente nos fortalecerá!",
"O período crítico da lua de mel é o café da manha...",
"O pessimista só vê o sol como fazedor de sombras.",
"O pior cego é aquele que anda sem bengala...",
"O primeiro ALT+L a gente nunca esquece...",
"O primeiro amor é apenas um pouco de tolice e muita curiosidade!",
"O problema das crianças é que elas nao sao descartáveis.",
"O problema de modem externo é aguentar a chuva...",
"O programa anti-corrupçao do Collor foi feito pelo Windows",
"O que fazer quando as tags acabam ???",
"O que fazer às 3 da manha? Compre um modem!",
"O rico pega o carro e sai, o pobre sai e o carro pega !",
"O saber e a razao falam, a ignorância e o erro rugem!",
"O segundo maior inimigo das mulheres: O Computador!",
"O serviço público é o último recurso dos incompetentes...",
"O sistema anticoncepcional da EVA era controlado pelo Windows",
"O sistema de segurança de J.Kennedy era controlado pelo Windows",
"O sonho näo acabou...Ass.: O Padeiro",
"O tempo é precioso, mas a verdade é muito mais.",
"O uisque e o melhor amigo do homem. O uisque é o cachorro engarrafado",
"O viaduto do Maluf foi projetado pelo Windows.",
"O xanpu contra calvície do Esperidiäo Amin foi feito pelo Windows",
"O zangao é a prova de que o golpe do baú sai caro...",
"Vestiba näo dorme... HIBERNA...",
"Vestiba näo reprova....     RENOVA SEUS CONHECIMENTOS...",
"Vicio de computador, até agora näo achei médico que cure...",
"Vida longa para o rei da horta! Viva o Rei Polho!",
"Vivia em Boston. Nao gostava do nome da cidade. Mudei pra Chicago.",
"Vivo correndo atrás da grana, mas ela sempre ganha!",
"Vivo ou morto, voce vem comigo!",
"Vivo perigosamente: Ando de moto sem capacete e uso o DblSpace.",
"Você já sonhou em hexadecimal?",
"Você nasceu em Pelotas??? - NAO!!!!Eu nasci inteiro!!!",
"Você näo pode ter tudo. Ia colocar aonde?",
"Você tem um micro? O meu é enorme...",
"Você, por exemplo, sequer sabe a diferença entre FERRO e AÇO",
"Vocês viram a namorada do Stevie Wonder? Nem ele...",
"Vovó já dizia... cobra que nao circula nao come rato!",
"Vá ver se estou lá na esquina, disse o mágico... Estava!",
"WINDOWS --> Agora para Mega Drive e Super Nintendo!",
"WOMAM.EXE  - é muito interativo, mas as vezes congela.",
"WOMEM.EXE - Otimo Programa, mas veio sem manual",
"Windows, uma maneira cara de diminuir o espaço no disco rígido..",
"Windows: A resposta pra uma pergunta que ninguém perguntou.",
"Windows: Näo-reciclável, Näo-biodegradável, e Näo-utilizável.",
"Windows: a 486 to XT conversion kit.",
"Xô bichano!! larga meu mouse...",
"de emocao a sua vida : faca pipocas com a panela aberta !",
"jogos via modem. A telepar agradece.....",
"mais vale um milhonário vivo do que um moralista morto.",
"mulher é que nem chuchu, quando pula o muro o vizinho come...",
"näo preciso comer nem beber. TENHO UM MODEM!!",
"É a geografia de uma garota que determina sua história.",
"É difícil de acreditar que mesmo seus amigos gostem dele.",
"É difícil de acreditar, mas alguns adolescente sao seres humanos.",
"É dos carecas que elas gozam mais...",
"É fácil admirar trabalho duro se você näo trabalha.",
"É mais fácil pegar moscas com mel do que com vinagre.",
"É melhor duas abelhas voando do que uma na mao...",
"É melhor saber coisas inúteis do que nao saber nada.",
"É o fim da picada, disse o viciado em drogas sobre a inflacao.",
"É o seu interior, e näo o exterior que conta.",
"É só a minha opiniäo (mas eu estou certo)",
"A saúde depende mais de precaução que dos médicos. (bisset)",
"A sorte está lançada. (julius cezar)",
"As feias que me perdoem mas beleza é fundamental. (vinícius de moraes)",
"Até tu brutus. (julius cezar)",
"Brasileiro gosta de levar vantagem em tudo. (gerson gomes)",
"Brasileiro sË fecha a porta depois de roubado.",
"Dívida externa não se paga, se administra. (ministro delfin neto)",
"Dois homens morrem com remorsos, quem teve e não gastou e quem teve e não ensinou. (montesquieu)",
"É mais fácil maldizer dos homens do que instruí-los e melhorá-los. (castro nery)",
"É melhor o pouco na memória que o muito no esquecimento. (hugh latimer)",
"Eu não estando podem até me bater. (sócrates)",
"Escoteiro é um menino vestido de idiota comandado por um idiota vestido de menino. (juca chaves)",
"Facilitar uma boa ação é mesmo que praticá-la. (maomé)",
"Filo por que quilo. (jânio da silva quadros)",
"Há algo de podre no reino da inglaterra.",
"Em terra de cego quem tem um olho só é caolho.",
"Meu amigo se diz foda, mas é ele que vive fudido.",
"Talvez eu esteja certo de ficar nervoso agora...",
"Tancredo Neves monitorava sua saúde com o Windows.",
"Tao fácil quanto 3.1415926535897932384626433832795028841.",
"Tarado é uma pessoa normal que é pega em flagrante.",
"Teclado nao instalado! <F1> para continuar...",
"Tecle + para ver outra TAGLINE.",
"Temos duas orelhas e uma boca. Deve ser para escutar mais e falar menos!",
"Tenho andado mais ocupado que telefone de BBS...",
"Tenho um amigo que só tem dois neurônios... e ainda um anula o outro!",
"Teorema de Pitágoras: a²=b²+c²  onde a, b e c säo letras do alfabeto",
"Teste pequeno: testículo. Logo, teste grande é um saco!",
"Testículo: Texto muito pequeno",
"Thesaurus: Antigo réptil com ótimo vocabulário...",
"Tirando a Jane Fonda, todas as feministas nao fazem uma mulher.",
"Toda doença tem uma cura:  OS/2  2.1.",
"Toda idéia valiosa ofende alguém.",
"Todas as frases que parecem verdadeiras de vem ser questionadas.",
"Todo corpo mergulhado numa banheira faz tocar o telefone...",
"Todo dia nasce um QI de ameba.",
"Todo gordo mija pelo metodo BRAILE!",
"Todo marido tem a infidelidade que merece...",
"Todo mundo tem alguma coisa a esconder...",
"Todo mundo é um gênio pelo menos uma vez por ano.",
"Todos erram na vida mas como sempre, os meus säo imperdoaveis.",
"Todos os cogumelos sao comestíveis. Alguns só uma vez...",
"Todos podem vencer, a nao ser que haja uma segunda pessoa.",
"Todos säo ignorantes, apenas em assuntos diferente.",
"Todos vao encontrar seu Waterloo um dia.",
"Tostines é fresco pque vende +, ou é viado por opçäo???",
"Trabalho duro melhora o futuro, mas a preguiça melhora o presente.",
"Trabalho em equipe permite que você ponha culpa em outro...",
"Traduçäo de joystick: bengala da alegria...",
"Traduçäo de nightmare: égua noturna...",
"Transformo se XT em PENTIUM usando apenas um grampo de cabelo...",
"Tripulante: Especialista em salto triplo",
"Tristeza de cornudo é sustentar a VACA !",
"Troco um cerebro usado por um computador novo. Pago diferenca.",
"Troque seu 486 por um 286 podre...",
"Troque um kilo de açúcar por uma caixa de nefrideos. Lá em Roma.",
"Três tipos de pessoa: As que sabem, e as que näo sabem contar.",
"Tu, piniquim. Eu, ropeu.",
"Tubaröes e Sysops, os únicos animais que näo precisam dormir...",
"Tudo bem chamar alguém de idiota; apenas näo prove.",
"Tudo na vida é passageiro, a näo ser o cobrador e o motorista.",
"Tudo ouço, tudo vejo, tudo digo mas...quem acredita?",
"Tudo que é grátis vale o que voce paga por ele",
"Tudo é ótimo quando em excesso...",
"UM MODEM NA MÄO E UMA IDEIA NA CABEÇA ... resulta tags idiotas por ai",
"UNÇÄO: erro de concordância. O correto seria (um é",
"Ultima mensagem recebida pelo Titanic: (Batemos devido a um iceBUG)",
"Um bebê consiste de dois buracos: um barulhento e um sujo!",
"Um bebê todo urinado e com nariz escorrendo nao é uma fofura.",
"a vida tem a cor vc penta",
"o MAL é a aucensia do AMOR. (ROQUEIRO INSANO)",
"Um brasileiro em Buenos Aires: Me dá un sorviete de muriango!"

];
var content = document.getElementById('content');
(function() {
	content.innerHTML= powerThoughts[Math.floor((Math.random() * 881) + 1)];
	var totalCount = 52;
    var num = Math.floor((Math.random() * totalCount) + 1);
    document.body.background = 'background/back' + num + '.jpg';
}());

