var powerThoughts = [
"Conservar algo que possa recordar-te seria admitir que eu pudesse esquecer-te (Shakespeare)✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Amigo é aquele que sabe tudo a seu respeito, e, mesmo assim,ainda gosta de você (Kim Hubbard)✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Ninguém é igual a ninguém. Todo ser humano é um estranho ímpar (Carlos Drummond de Andrade)✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Se você obedece a todas as regras, acaba perdendo toda a  diversão (Katherine Hepburn)✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"O prazer dos grandes homens consiste em tornar os outros mais  felizes (Pascal)✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Só se vê bem com os olhos do coração. O essencial é invisível aos olho (St. Exupéry)✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Quando um homem não encontra a si mesmo, não encontra a nada (Goethe)",
"O homem de bem exige tudo de si próprio; o homem medíocre espera tudo dos outros (Confúcio)✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Se você quer alcançar a grandeza, pare de pedir permissão. ~Anônimo",
"As coisas funcionam melhor para aqueles que fazem o melhor de como as coisas funcionam. ~John Wooden✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Para viver uma vida criativa, devemos perder o medo de estar errado. ~Anônimo✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Se você não está disposto a arriscar o usual, terá que se contentar com o comum. ~Jim Rohn✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Confie porque você está disposto a aceitar o risco, não porque é seguro ou certo. ~Anônimo",
"Todos os nossos sonhos podem se tornar realidade se tivermos coragem de persegui-los. ~Walt Disney✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Coisas boas vêm para as pessoas que esperam, mas coisas melhores vêm para aqueles que saem e as pegam. ~Anônimo✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Se você fizer o que sempre fez, obterá o que sempre obteve. ~Anônimo✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"O sucesso é caminhar de fracasso em fracasso sem perder o entusiasmo. ~Winston Churchill✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Apenas quando a lagarta pensou que o mundo estava acabando, ela se transformou em borboleta. ~Provérbio✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Empreendedores de sucesso são doadores e não receptores de energia positiva. ~Anônimo✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Sempre que você vê uma pessoa de sucesso, você só vê as glórias públicas, nunca os sacrifícios privados para alcançá-las. ~Vaibhav Shah✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"As oportunidades não acontecem, você as cria. ~Chris Grosser✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Tente não se tornar uma pessoa de sucesso, mas tente se tornar uma pessoa de valor. ~Albert Einstein✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Grandes mentes discutem ideias; mentes medianas discutem eventos; mentes pequenas discutem pessoas. ~Eleanor Roosevelt✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Eu não falhei. Acabei de encontrar 10.000 maneiras que não funcionam. ~Thomas A. Edison",
"Se você não valoriza seu tempo, os outros também não. Pare de dar seu tempo e talentos - comece a cobrar por isso. ~Kim Garst✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Um homem de sucesso é aquele que pode estabelecer uma base firme com os tijolos que outros jogaram nele. ~David Brinkley✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Ninguém pode fazer você se sentir inferior sem o seu consentimento. ~Eleanor Roosevelt",
"Todo o segredo de uma vida bem-sucedida é descobrir qual é o destino de alguém fazer e depois fazê-lo. ~Henry Ford✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Se você está passando pelo inferno, continue. ~Winston Churchill✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Aqueles que são loucos o suficiente para pensar que podem mudar o mundo, são os que o fazem. ~Steve Jobs✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Não levante a voz, melhore seu argumento. ~Anônimo✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"O que nos parece provações amargas são muitas vezes bênçãos disfarçadas. ~ Oscar Wilde✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"O sentido da vida é encontrar o seu dom. O propósito da vida é dá-lo. ~Anônimo✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"A distância entre insanidade e genialidade é medida apenas pelo sucesso. ~Bruce Feirstein✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Quando você para de perseguir as coisas erradas, você dá às coisas certas uma chance de te pegar. ~Lolly Daskal✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Não tenha medo de desistir do bom em busca do ótimo. ~John D. Rockefeller✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Nenhuma obra-prima foi criada por um artista preguiçoso.~ Anônimo✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"A felicidade é uma borboleta que, quando perseguida, está sempre além do seu alcance, mas que, se você se sentar tranquilamente, pode pousar sobre você. ~Nathaniel Hawthorne✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Se você não consegue explicar de forma simples, você não entende bem o suficiente. ~Albert Einstein✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Bem-aventurados aqueles que podem dar sem lembrar e receber sem esquecer. ~Anônimo✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Faça uma coisa todos os dias que te assusta. ~Anônimo✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Qual é o sentido de estar vivo se você não tenta pelo menos fazer algo notável. ~Anônimo✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"A vida não é sobre encontrar a si mesmo. A vida é sobre criar a si mesmo. ~Lolly Daskal✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Nada no mundo é mais comum do que pessoas mal sucedidas com talento. ~Anônimo✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Conhecimento é estar ciente do que você pode fazer. Sabedoria é saber quando não fazer. ~Anônimo✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Seu problema não é o problema. Sua reação é o problema. ~Anônimo✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Você pode fazer qualquer coisa, mas não tudo. ~Anônimo✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"A inovação distingue entre um líder e um seguidor. ~Steve Jobs✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Existem dois tipos de pessoas que vão te dizer que você não pode fazer a diferença neste mundo: aqueles que têm medo de tentar e aqueles que têm medo de você ter sucesso. ~Ray Goforth✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"O pensamento deve se tornar seu ativo capital, não importa os altos e baixos que você encontre em sua vida. ~Dr. APJ Kalam✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Eu acho que quanto mais eu trabalho, mais sorte eu pareço ter. ~Thomas Jefferson✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"O ponto de partida de toda conquista é o desejo. ~Napolean Hill✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"O sucesso é a soma de pequenos esforços, repetidos dia após dia. ~Robert Collier✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Se você quer alcançar a excelência, você pode chegar lá hoje. A partir deste segundo, pare de fazer um trabalho menos que excelente. ~Thomas J. Watson✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Todo o progresso ocorre fora da zona de conforto. ~Michael John Bobak✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Você só pode ter sucesso se desejar ter sucesso; você só pode falhar se não se importar em falhar. ~Philippos✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Coragem é resistência ao medo, domínio do medo - não ausência do medo. ~Mark Twain✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Apenas deixe para amanhã o que você está disposto a morrer deixando de fazer. ~Pablo Picasso✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"As pessoas costumam dizer que a motivação não dura. Bem, nem o banho - é por isso que o recomendamos diariamente. ~Zig Ziglar✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Nós nos tornamos o que pensamos a maior parte do tempo, e esse é o segredo mais estranho. ~Earl Nightingale✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"O único lugar onde o sucesso vem antes do trabalho é no dicionário. ~Vidal Sassoon✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"A melhor razão para começar uma organização é fazer sentido; criar um produto ou serviço para tornar o mundo um lugar melhor. ~Guy Kawasaki✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Eu acho que quando você tem um interesse real na vida e uma vida curiosa, o sono não é a coisa mais importante. ~Martha Stewart",
"Não é o que você olha que importa, é o que você vê. ~Anônimo✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"O caminho para o sucesso e o caminho para o fracasso são quase exatamente os mesmos. ~Colin R. Davis✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"A função da liderança é produzir mais líderes, não mais seguidores. ~Ralph Nader✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Sucesso é gostar de si mesmo, gostar do que você faz e gostar de como você faz. ~Maya Angelou✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"À medida que olhamos para o próximo século, os líderes serão aqueles que capacitam os outros. ~Bill Gates✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Um verdadeiro empreendedor é alguém que não tem uma rede de segurança por baixo de si. ~Henry Kravis✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"O primeiro passo para o sucesso é dado quando você se recusa a ser cativo do ambiente em que se encontra pela primeira vez. ~Mark Caine✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Quando eu ouso ser poderoso - usar minha força a serviço da minha visão, então se torna cada vez menos importante se eu tenho medo. ~Audre Lorde✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Sempre que você se encontra do lado da maioria, é hora de parar e refletir. ~Mark Twain✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"O guerreiro de sucesso é o homem comum, com foco de laser. ~Bruce Lee✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Desenvolva o sucesso dos fracassos. O desânimo e o fracasso são dois dos degraus mais seguros para o sucesso. ~Dale Carnegie",
"Se você não desenhar seu próprio plano de vida, é provável que você caia no plano de outra pessoa. E adivinhe o que eles planejaram para você? Não muito. ~ Jim Rohn✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Se você realmente quer algo, não espere por isso - ensine-se a ser impaciente. ~Gurbaksh Chahal✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Não deixe que o medo de perder seja maior do que a emoção de ganhar. ~Robert Kiyosaki✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Se você quer fazer uma mudança permanente, pare de focar no tamanho dos seus problemas e comece a focar no tamanho de você! ~T. Harv Eker✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Pessoas bem sucedidas fazem o que as pessoas mal sucedidas não estão dispostas a fazer. Não deseje que fosse mais fácil, gostaria que você fosse melhor. ~Jim Rohn✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"A razão número um pela qual as pessoas falham na vida é porque elas ouvem seus amigos, familiares e vizinhos. ~Napoleon Hill✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Na minha experiência, há apenas uma motivação, que é o desejo. Nenhuma razão ou princípio o contém ou se opõe a ele. ~Jane Smiley✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"O sucesso não consiste em nunca cometer erros, mas em nunca cometer o mesmo uma segunda vez. ~George Bernard Shaw✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Eu não quero chegar ao fim da minha vida e descobrir que vivi apenas o comprimento dela. Eu quero ter vivido a largura dela também. ~Diane Ackerman✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Você deve esperar grandes coisas de si mesmo antes de poder fazê-las. ~Michael Jordan✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Motivação é o que faz você começar. Hábito é o que faz você continuar. ~Jim Ryun✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"As pessoas raramente têm sucesso a menos que se divirtam no que estão fazendo. ~Dale Carnegie✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Não há nenhuma chance, nenhum destino, nenhum destino, que possa impedir ou controlar a firme determinação de uma alma determinada. ~Ella Wheeler Wilcox✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Nosso maior medo não deve ser o fracasso, mas o sucesso em coisas da vida que realmente não importam. ~Francis Chan✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Você precisa acordar todas as manhãs com determinação se quiser ir para a cama com satisfação. ~George Lorimer✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Para ter sucesso você deve aceitar todos os desafios que surgirem no seu caminho. Você não pode simplesmente aceitar os que você gosta. ~Mike Gafka✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Sucesso é... conhecer seu propósito na vida, crescer para alcançar seu potencial máximo e plantar sementes que beneficiem os outros. ~ John C. Maxwell✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Seja miserável. Ou motive-se. O que quer que tenha que ser feito, é sempre sua escolha. ~Wayne Dyer✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Para realizar grandes coisas, devemos não apenas agir, mas também sonhar, não apenas planejar, mas também acreditar.~ Anatole France✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"A maioria das coisas importantes do mundo foram realizadas por pessoas que continuaram tentando quando parecia não haver nenhuma ajuda. ~Dale Carnegie✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Você mede o tamanho da conquista pelos obstáculos que teve que superar para alcançar seus objetivos. ~Booker T. Washington✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Dificuldades reais podem ser superadas; são apenas as imaginárias que são invencíveis. ~Theodore N. Vail✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"É melhor falhar na originalidade do que ter sucesso na imitação. Herman Melville✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"A sorte fica do lado de quem ousa. Virgil✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"As pequenas mentes são domadas e subjugadas pelo infortúnio; mas as grandes mentes se elevam acima dele. Washington Irving✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"O fracasso é o condimento que dá sabor ao sucesso. ~Truman Capote✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Não deixe que o que você não pode fazer interfira no que você pode fazer. John R. Wooden✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Você pode ter que lutar uma batalha mais de uma vez para vencê-la. Margaret Thatcher✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Fique com fome, fique tolo. Steve Jobs✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Faça ou morra. renato sousa✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"Seja a mudança que você quer ver no mundo. renato sousa✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥",
"A vida tem a cor vc pinta. meninozinho manso✿⊰『 Codigos Das Carinhas 』( ͡° ͜ʖ ͡°)/••♥"
];

var content = document.getElementById('content');
(function() {
	content.innerHTML= powerThoughts[Math.floor((Math.random() * 105) + 1)];
	var totalCount = 52;
    var num = Math.floor((Math.random() * totalCount) + 1);
    document.body.background = 'background/back' + num + '.jpg';
}());
