var powerThoughts = [
"Se você quer alcançar a grandeza, pare de pedir permissão. ~Anônimo",
"As coisas funcionam melhor para aqueles que fazem o melhor de como as coisas funcionam. ~John Wooden",
"Para viver uma vida criativa, devemos perder o medo de estar errado. ~Anônimo",
"Se você não está disposto a arriscar o usual, terá que se contentar com o comum. ~Jim Rohn",
"Confie porque você está disposto a aceitar o risco, não porque é seguro ou certo. ~Anônimo",
"Todos os nossos sonhos podem se tornar realidade se tivermos coragem de persegui-los. ~Walt Disney",
"Coisas boas vêm para as pessoas que esperam, mas coisas melhores vêm para aqueles que saem e as pegam. ~Anônimo",
"Se você fizer o que sempre fez, obterá o que sempre obteve. ~Anônimo",
"O sucesso é caminhar de fracasso em fracasso sem perder o entusiasmo. ~Winston Churchill",
"Apenas quando a lagarta pensou que o mundo estava acabando, ela se transformou em borboleta. ~Provérbio",
"Empreendedores de sucesso são doadores e não receptores de energia positiva. ~Anônimo",
"Sempre que você vê uma pessoa de sucesso, você só vê as glórias públicas, nunca os sacrifícios privados para alcançá-las. ~Vaibhav Shah",
"As oportunidades não acontecem, você as cria. ~Chris Grosser",
"Tente não se tornar uma pessoa de sucesso, mas tente se tornar uma pessoa de valor. ~Albert Einstein",
"Grandes mentes discutem ideias; mentes medianas discutem eventos; mentes pequenas discutem pessoas. ~Eleanor Roosevelt",
"Eu não falhei. Acabei de encontrar 10.000 maneiras que não funcionam. ~Thomas A. Edison",
"Se você não valoriza seu tempo, os outros também não. Pare de dar seu tempo e talentos - comece a cobrar por isso. ~Kim Garst",
"Um homem de sucesso é aquele que pode estabelecer uma base firme com os tijolos que outros jogaram nele. ~David Brinkley",
"Ninguém pode fazer você se sentir inferior sem o seu consentimento. ~Eleanor Roosevelt",
"Todo o segredo de uma vida bem-sucedida é descobrir qual é o destino de alguém fazer e depois fazê-lo. ~Henry Ford",
"Se você está passando pelo inferno, continue. ~Winston Churchill",
"Aqueles que são loucos o suficiente para pensar que podem mudar o mundo, são os que o fazem. ~Steve Jobs",
"Não levante a voz, melhore seu argumento. ~Anônimo",
"O que nos parece provações amargas são muitas vezes bênçãos disfarçadas. ~ Oscar Wilde",
"O sentido da vida é encontrar o seu dom. O propósito da vida é dá-lo. ~Anônimo",
"A distância entre insanidade e genialidade é medida apenas pelo sucesso. ~Bruce Feirstein",
"Quando você para de perseguir as coisas erradas, você dá às coisas certas uma chance de te pegar. ~Lolly Daskal",
"Não tenha medo de desistir do bom em busca do ótimo. ~John D. Rockefeller",
"Nenhuma obra-prima foi criada por um artista preguiçoso.~ Anônimo",
"A felicidade é uma borboleta que, quando perseguida, está sempre além do seu alcance, mas que, se você se sentar tranquilamente, pode pousar sobre você. ~Nathaniel Hawthorne",
"Se você não consegue explicar de forma simples, você não entende bem o suficiente. ~Albert Einstein",
"Bem-aventurados aqueles que podem dar sem lembrar e receber sem esquecer. ~Anônimo",
"Faça uma coisa todos os dias que te assusta. ~Anônimo",
"Qual é o sentido de estar vivo se você não tenta pelo menos fazer algo notável. ~Anônimo",
"A vida não é sobre encontrar a si mesmo. A vida é sobre criar a si mesmo. ~Lolly Daskal",
"Nada no mundo é mais comum do que pessoas mal sucedidas com talento. ~Anônimo",
"Conhecimento é estar ciente do que você pode fazer. Sabedoria é saber quando não fazer. ~Anônimo",
"Seu problema não é o problema. Sua reação é o problema. ~Anônimo",
"Você pode fazer qualquer coisa, mas não tudo. ~Anônimo",
"A inovação distingue entre um líder e um seguidor. ~Steve Jobs",
"Existem dois tipos de pessoas que vão te dizer que você não pode fazer a diferença neste mundo: aqueles que têm medo de tentar e aqueles que têm medo de você ter sucesso. ~Ray Goforth",
"O pensamento deve se tornar seu ativo capital, não importa os altos e baixos que você encontre em sua vida. ~Dr. APJ Kalam",
"Eu acho que quanto mais eu trabalho, mais sorte eu pareço ter. ~Thomas Jefferson",
"O ponto de partida de toda conquista é o desejo. ~Napolean Hill",
"O sucesso é a soma de pequenos esforços, repetidos dia após dia. ~Robert Collier",
"Se você quer alcançar a excelência, você pode chegar lá hoje. A partir deste segundo, pare de fazer um trabalho menos que excelente. ~Thomas J. Watson",
"Todo o progresso ocorre fora da zona de conforto. ~Michael John Bobak",
"Você só pode ter sucesso se desejar ter sucesso; você só pode falhar se não se importar em falhar. ~Philippos",
"Coragem é resistência ao medo, domínio do medo - não ausência do medo. ~Mark Twain",
"Apenas deixe para amanhã o que você está disposto a morrer deixando de fazer. ~Pablo Picasso",
"As pessoas costumam dizer que a motivação não dura. Bem, nem o banho - é por isso que o recomendamos diariamente. ~Zig Ziglar",
"Nós nos tornamos o que pensamos a maior parte do tempo, e esse é o segredo mais estranho. ~Earl Nightingale",
"O único lugar onde o sucesso vem antes do trabalho é no dicionário. ~Vidal Sassoon",
"A melhor razão para começar uma organização é fazer sentido; criar um produto ou serviço para tornar o mundo um lugar melhor. ~Guy Kawasaki",
"Eu acho que quando você tem um interesse real na vida e uma vida curiosa, o sono não é a coisa mais importante. ~Martha Stewart",
"Não é o que você olha que importa, é o que você vê. ~Anônimo",
"O caminho para o sucesso e o caminho para o fracasso são quase exatamente os mesmos. ~Colin R. Davis",
"A função da liderança é produzir mais líderes, não mais seguidores. ~Ralph Nader",
"Sucesso é gostar de si mesmo, gostar do que você faz e gostar de como você faz. ~Maya Angelou",
"À medida que olhamos para o próximo século, os líderes serão aqueles que capacitam os outros. ~Bill Gates",
"Um verdadeiro empreendedor é alguém que não tem uma rede de segurança por baixo de si. ~Henry Kravis",
"O primeiro passo para o sucesso é dado quando você se recusa a ser cativo do ambiente em que se encontra pela primeira vez. ~Mark Caine",
"Quando eu ouso ser poderoso - usar minha força a serviço da minha visão, então se torna cada vez menos importante se eu tenho medo. ~Audre Lorde",
"Sempre que você se encontra do lado da maioria, é hora de parar e refletir. ~Mark Twain",
"O guerreiro de sucesso é o homem comum, com foco de laser. ~Bruce Lee",
"Desenvolva o sucesso dos fracassos. O desânimo e o fracasso são dois dos degraus mais seguros para o sucesso. ~Dale Carnegie",
"Se você não desenhar seu próprio plano de vida, é provável que você caia no plano de outra pessoa. E adivinhe o que eles planejaram para você? Não muito. ~ Jim Rohn",
"Se você realmente quer algo, não espere por isso - ensine-se a ser impaciente. ~Gurbaksh Chahal",
"Não deixe que o medo de perder seja maior do que a emoção de ganhar. ~Robert Kiyosaki",
"Se você quer fazer uma mudança permanente, pare de focar no tamanho dos seus problemas e comece a focar no tamanho de você! ~T. Harv Eker",
"Pessoas bem sucedidas fazem o que as pessoas mal sucedidas não estão dispostas a fazer. Não deseje que fosse mais fácil, gostaria que você fosse melhor. ~Jim Rohn",
"A razão número um pela qual as pessoas falham na vida é porque elas ouvem seus amigos, familiares e vizinhos. ~Napoleon Hill",
"Na minha experiência, há apenas uma motivação, que é o desejo. Nenhuma razão ou princípio o contém ou se opõe a ele. ~Jane Smiley",
"O sucesso não consiste em nunca cometer erros, mas em nunca cometer o mesmo uma segunda vez. ~George Bernard Shaw",
"Eu não quero chegar ao fim da minha vida e descobrir que vivi apenas o comprimento dela. Eu quero ter vivido a largura dela também. ~Diane Ackerman",
"Você deve esperar grandes coisas de si mesmo antes de poder fazê-las. ~Michael Jordan",
"Motivação é o que faz você começar. Hábito é o que faz você continuar. ~Jim Ryun",
"As pessoas raramente têm sucesso a menos que se divirtam no que estão fazendo. ~Dale Carnegie",
"Não há nenhuma chance, nenhum destino, nenhum destino, que possa impedir ou controlar a firme determinação de uma alma determinada. ~Ella Wheeler Wilcox",
"Nosso maior medo não deve ser o fracasso, mas o sucesso em coisas da vida que realmente não importam. ~Francis Chan",
"Você precisa acordar todas as manhãs com determinação se quiser ir para a cama com satisfação. ~George Lorimer",
"Para ter sucesso você deve aceitar todos os desafios que surgirem no seu caminho. Você não pode simplesmente aceitar os que você gosta. ~Mike Gafka",
"Sucesso é... conhecer seu propósito na vida, crescer para alcançar seu potencial máximo e plantar sementes que beneficiem os outros. ~ John C. Maxwell",
"Seja miserável. Ou motive-se. O que quer que tenha que ser feito, é sempre sua escolha. ~Wayne Dyer",
"Para realizar grandes coisas, devemos não apenas agir, mas também sonhar, não apenas planejar, mas também acreditar.~ Anatole France",
"A maioria das coisas importantes do mundo foram realizadas por pessoas que continuaram tentando quando parecia não haver nenhuma ajuda. ~Dale Carnegie",
"Você mede o tamanho da conquista pelos obstáculos que teve que superar para alcançar seus objetivos. ~Booker T. Washington",
"Dificuldades reais podem ser superadas; são apenas as imaginárias que são invencíveis. ~Theodore N. Vail",
"É melhor falhar na originalidade do que ter sucesso na imitação. ~Herman Melville",
"A sorte fica do lado de quem ousa. ~Virgil",
"As pequenas mentes são domadas e subjugadas pelo infortúnio; mas as grandes mentes se elevam acima dele. ~Washington Irving",
"O fracasso é o condimento que dá sabor ao sucesso. ~Truman Capote",
"Não deixe que o que você não pode fazer interfira no que você pode fazer. ~John R. Wooden",
"Você pode ter que lutar uma batalha mais de uma vez para vencê-la. ~Margaret Thatcher",
"Fique com fome, fique tolo. ~Steve Jobs",
"Faça ou morra. ~Mahatama Gandhi",
"Seja a mudança que você quer ver no mundo. ~Mahatama Gandhi",
"A Challenger tinha sistema de segurança projetado pelo Windows",
"A Inteligência artificial nao funciona por causa da Burrice Natural.",
"A Kaiser dá dor de cabeca... ninguém pode negar!",
"A bebida mata lentamente! E daí? Nao estou com pressa...",
"A beleza nao esta apenas nas curvas, esta tambem nas vias de acesso.",
"A cal é virgem porque o pincel é brocha!",
"A carne näo aumentou, o boi é que diminuiu.",
"A chance dessa tag ser selecionada era de uma em 1040!",
"A clara do ovo e o açúcar, no forno, suspiravam...",
"A coisa mais profunda em certas mulheres é o sono!",
"A esperança e a sogra sao sempre as últimas a morrer...",
"A esperança é a última que morre.... MAS MORRE!!!",
"A felicidade de cada Calouro está na morte de cada Veterano!!!",
"A felicidade se constrói a partir das pequenas coisas feitas com amor.",
"A fita é virgem porque o gravador é stéreo",
"A fortuna faz amigos. A desgraça prova se eles existem de fato.",
"A história se repete porque ninguém presta atençao.",
"A ignorancia é temporária, a estupidez nao.",
"A imaginaçao é mais importante que o conhecimento...",
"A informaçäo mais necessária é sempre a menos disponível.",
"A ligaçäo caiu. Será que ela se machucou muito ??",
"A mata é virgem porque o vento é fresco",
"A melhor defesa contra lógica é estupidez.",
"A mente, como os pára-quedas, só funcionam quando abertas.",
"A modéstia morreu quando a falsa modéstia nasceu.",
"A modéstia é uma das minhas inúmeras virtudes...",
"A mulher chora antes do casamento; o homem depois.",
"A mulher do vizinho é sempre mais magra que a nossa...",
"A namorada disse para o namorado: "Olha o guarda, guarda!",
"A namorada disse para o namorado: "Olha o tira, tira!",
"A pior coisa da censura é .",
"A pior coisa do sexo oral é a vista...",
"A pomba é o passarinho da Paz, e a mulher a paz do passarinho !",
"A primeira amnésia a gente nunca esquece !",
"A proteçao anti-bomba do World Trade Center era feita por Windows",
"A sensaçao é boa, mas a posiçao é ridícula!",
"A sensibilidade de um homem está na força do seu punho.",
"A tagline da mensagem anterior é ridicula.",
"A tcla do mu tclado stá com um pquno problminha...",
"A teimosia é a força de vontade do chato.",
"A terra está 98% cheia. Delete quem voce puder.",
"A verdade é fruto do tempo, e nao da autoridade...",
"A vida começa aos 14.4K",
"A vida nao é um conto de fadas, mas um conto de fatos...",
"A vida se vive para frente, mas se entende para trás.",
"A vida é imprevisível... Coma a sobremesa antes!",
"A vida é uma doença sexualmente transmissível.",
"A vingança tarda mais näo falha!!!",
"A virgindade é curável, se detectada cedo!",
"A véia Quacker, a avó do mingau...",
"A última palavra é sempre da mulher: SIM SENHOR !!!",
"A: nao encontrado... B: nao encontrado... formatando C:...",
"ABISMADO: Pessoa que sofreu queda em abismo",
"AMOR: 4 letras de felicidade... ADEUS: 5 letras que choram...",
"ATENCAO: Feche a DOOR quando sair! Ass: Sysop.",
"ATENÇAO, todos dados do disco rígido serao apagados. Continua (S/S)?",
"ATROPELADO: Nú Artístico",
"AVISO! É proibido por lei remover esta tagline!",
"Abandone as esperanças aquele que posta mensagens aqui.",
"Abandone as esperanças aquele que teclar --+ aqui.",
"Abismo? Que abiiiiiiiiiiiiiiiiiiiiiiiiiisssssssssssmmo...",
"Acelere seu XT: 9.8 m/s²",
"Acentua&@o % um problema que j$ foi superado.",
"Acha seu 286 lento? Volte a usar um TK!",
"Acho qUe miNHa TEclA CaPS loCk eSta COm dEfeIto...",
"Acho que penso, logo acho que existo...",
"Acho que vou fazer umas Tag's hoje..."
];
var content = document.getElementById('content');
(function() {
	content.innerHTML= powerThoughts[Math.floor((Math.random() * 96) + 1)];
	var totalCount = 52;
    var num = Math.floor((Math.random() * totalCount) + 1);
    document.body.background = 'background/back' + num + '.jpg';
}());

