var powerThoughts = [
"Se você quer alcançar a grandeza, pare de pedir permissão. ~Anônimo",
"As coisas funcionam melhor para aqueles que fazem o melhor de como as coisas funcionam. ~John Wooden",
"Para viver uma vida criativa, devemos perder o medo de estar errado. ~Anônimo",
"Se você não está disposto a arriscar o usual, terá que se contentar com o comum. ~Jim Rohn",
"Confie porque você está disposto a aceitar o risco, não porque é seguro ou certo. ~Anônimo",
"Todos os nossos sonhos podem se tornar realidade se tivermos coragem de persegui-los. ~Walt Disney",
"Coisas boas vêm para as pessoas que esperam, mas coisas melhores vêm para aqueles que saem e as pegam. ~Anônimo",
"Se você fizer o que sempre fez, obterá o que sempre obteve. ~Anônimo",
"O sucesso é caminhar de fracasso em fracasso sem perder o entusiasmo. ~Winston Churchill",
"Apenas quando a lagarta pensou que o mundo estava acabando, ela se transformou em borboleta. ~Provérbio",
"Empreendedores de sucesso são doadores e não receptores de energia positiva. ~Anônimo",
"Sempre que você vê uma pessoa de sucesso, você só vê as glórias públicas, nunca os sacrifícios privados para alcançá-las. ~Vaibhav Shah",
"As oportunidades não acontecem, você as cria. ~Chris Grosser",
"Tente não se tornar uma pessoa de sucesso, mas tente se tornar uma pessoa de valor. ~Albert Einstein",
"Grandes mentes discutem ideias; mentes medianas discutem eventos; mentes pequenas discutem pessoas. ~Eleanor Roosevelt",
"Eu não falhei. Acabei de encontrar 10.000 maneiras que não funcionam. ~Thomas A. Edison",
"Se você não valoriza seu tempo, os outros também não. Pare de dar seu tempo e talentos - comece a cobrar por isso. ~Kim Garst",
"Um homem de sucesso é aquele que pode estabelecer uma base firme com os tijolos que outros jogaram nele. ~David Brinkley",
"Ninguém pode fazer você se sentir inferior sem o seu consentimento. ~Eleanor Roosevelt",
"Todo o segredo de uma vida bem-sucedida é descobrir qual é o destino de alguém fazer e depois fazê-lo. ~Henry Ford",
"Se você está passando pelo inferno, continue. ~Winston Churchill",
"Aqueles que são loucos o suficiente para pensar que podem mudar o mundo, são os que o fazem. ~Steve Jobs",
"Não levante a voz, melhore seu argumento. ~Anônimo",
"O que nos parece provações amargas são muitas vezes bênçãos disfarçadas. ~ Oscar Wilde",
"O sentido da vida é encontrar o seu dom. O propósito da vida é dá-lo. ~Anônimo",
"A distância entre insanidade e genialidade é medida apenas pelo sucesso. ~Bruce Feirstein",
"Quando você para de perseguir as coisas erradas, você dá às coisas certas uma chance de te pegar. ~Lolly Daskal",
"Não tenha medo de desistir do bom em busca do ótimo. ~John D. Rockefeller",
"Nenhuma obra-prima foi criada por um artista preguiçoso.~ Anônimo",
"A felicidade é uma borboleta que, quando perseguida, está sempre além do seu alcance, mas que, se você se sentar tranquilamente, pode pousar sobre você. ~Nathaniel Hawthorne",
"Se você não consegue explicar de forma simples, você não entende bem o suficiente. ~Albert Einstein",
"Bem-aventurados aqueles que podem dar sem lembrar e receber sem esquecer. ~Anônimo",
"Faça uma coisa todos os dias que te assusta. ~Anônimo",
"Qual é o sentido de estar vivo se você não tenta pelo menos fazer algo notável. ~Anônimo",
"A vida não é sobre encontrar a si mesmo. A vida é sobre criar a si mesmo. ~Lolly Daskal",
"Nada no mundo é mais comum do que pessoas mal sucedidas com talento. ~Anônimo",
"Conhecimento é estar ciente do que você pode fazer. Sabedoria é saber quando não fazer. ~Anônimo",
"Seu problema não é o problema. Sua reação é o problema. ~Anônimo",
"Você pode fazer qualquer coisa, mas não tudo. ~Anônimo",
"A inovação distingue entre um líder e um seguidor. ~Steve Jobs",
"Existem dois tipos de pessoas que vão te dizer que você não pode fazer a diferença neste mundo: aqueles que têm medo de tentar e aqueles que têm medo de você ter sucesso. ~Ray Goforth",
"O pensamento deve se tornar seu ativo capital, não importa os altos e baixos que você encontre em sua vida. ~Dr. APJ Kalam",
"Eu acho que quanto mais eu trabalho, mais sorte eu pareço ter. ~Thomas Jefferson",
"O ponto de partida de toda conquista é o desejo. ~Napolean Hill",
"O sucesso é a soma de pequenos esforços, repetidos dia após dia. ~Robert Collier",
"Se você quer alcançar a excelência, você pode chegar lá hoje. A partir deste segundo, pare de fazer um trabalho menos que excelente. ~Thomas J. Watson",
"Todo o progresso ocorre fora da zona de conforto. ~Michael John Bobak",
"Você só pode ter sucesso se desejar ter sucesso; você só pode falhar se não se importar em falhar. ~Philippos",
"Coragem é resistência ao medo, domínio do medo - não ausência do medo. ~Mark Twain",
"Apenas deixe para amanhã o que você está disposto a morrer deixando de fazer. ~Pablo Picasso",
"As pessoas costumam dizer que a motivação não dura. Bem, nem o banho - é por isso que o recomendamos diariamente. ~Zig Ziglar",
"Nós nos tornamos o que pensamos a maior parte do tempo, e esse é o segredo mais estranho. ~Earl Nightingale",
"O único lugar onde o sucesso vem antes do trabalho é no dicionário. ~Vidal Sassoon",
"A melhor razão para começar uma organização é fazer sentido; criar um produto ou serviço para tornar o mundo um lugar melhor. ~Guy Kawasaki",
"Eu acho que quando você tem um interesse real na vida e uma vida curiosa, o sono não é a coisa mais importante. ~Martha Stewart",
"Não é o que você olha que importa, é o que você vê. ~Anônimo",
"O caminho para o sucesso e o caminho para o fracasso são quase exatamente os mesmos. ~Colin R. Davis",
"A função da liderança é produzir mais líderes, não mais seguidores. ~Ralph Nader",
"Sucesso é gostar de si mesmo, gostar do que você faz e gostar de como você faz. ~Maya Angelou",
"À medida que olhamos para o próximo século, os líderes serão aqueles que capacitam os outros. ~Bill Gates",
"Um verdadeiro empreendedor é alguém que não tem uma rede de segurança por baixo de si. ~Henry Kravis",
"O primeiro passo para o sucesso é dado quando você se recusa a ser cativo do ambiente em que se encontra pela primeira vez. ~Mark Caine",
"Quando eu ouso ser poderoso - usar minha força a serviço da minha visão, então se torna cada vez menos importante se eu tenho medo. ~Audre Lorde",
"Sempre que você se encontra do lado da maioria, é hora de parar e refletir. ~Mark Twain",
"O guerreiro de sucesso é o homem comum, com foco de laser. ~Bruce Lee",
"Desenvolva o sucesso dos fracassos. O desânimo e o fracasso são dois dos degraus mais seguros para o sucesso. ~Dale Carnegie",
"Se você não desenhar seu próprio plano de vida, é provável que você caia no plano de outra pessoa. E adivinhe o que eles planejaram para você? Não muito. ~ Jim Rohn",
"Se você realmente quer algo, não espere por isso - ensine-se a ser impaciente. ~Gurbaksh Chahal",
"Não deixe que o medo de perder seja maior do que a emoção de ganhar. ~Robert Kiyosaki",
"Se você quer fazer uma mudança permanente, pare de focar no tamanho dos seus problemas e comece a focar no tamanho de você! ~T. Harv Eker",
"Pessoas bem sucedidas fazem o que as pessoas mal sucedidas não estão dispostas a fazer. Não deseje que fosse mais fácil, gostaria que você fosse melhor. ~Jim Rohn",
"A razão número um pela qual as pessoas falham na vida é porque elas ouvem seus amigos, familiares e vizinhos. ~Napoleon Hill",
"Na minha experiência, há apenas uma motivação, que é o desejo. Nenhuma razão ou princípio o contém ou se opõe a ele. ~Jane Smiley",
"O sucesso não consiste em nunca cometer erros, mas em nunca cometer o mesmo uma segunda vez. ~George Bernard Shaw",
"Eu não quero chegar ao fim da minha vida e descobrir que vivi apenas o comprimento dela. Eu quero ter vivido a largura dela também. ~Diane Ackerman",
"Você deve esperar grandes coisas de si mesmo antes de poder fazê-las. ~Michael Jordan",
"Motivação é o que faz você começar. Hábito é o que faz você continuar. ~Jim Ryun",
"As pessoas raramente têm sucesso a menos que se divirtam no que estão fazendo. ~Dale Carnegie",
"Não há nenhuma chance, nenhum destino, nenhum destino, que possa impedir ou controlar a firme determinação de uma alma determinada. ~Ella Wheeler Wilcox",
"Nosso maior medo não deve ser o fracasso, mas o sucesso em coisas da vida que realmente não importam. ~Francis Chan",
"Você precisa acordar todas as manhãs com determinação se quiser ir para a cama com satisfação. ~George Lorimer",
"Para ter sucesso você deve aceitar todos os desafios que surgirem no seu caminho. Você não pode simplesmente aceitar os que você gosta. ~Mike Gafka",
"Sucesso é... conhecer seu propósito na vida, crescer para alcançar seu potencial máximo e plantar sementes que beneficiem os outros. ~ John C. Maxwell",
"Seja miserável. Ou motive-se. O que quer que tenha que ser feito, é sempre sua escolha. ~Wayne Dyer",
"Para realizar grandes coisas, devemos não apenas agir, mas também sonhar, não apenas planejar, mas também acreditar.~ Anatole France",
"A maioria das coisas importantes do mundo foram realizadas por pessoas que continuaram tentando quando parecia não haver nenhuma ajuda. ~Dale Carnegie",
"Você mede o tamanho da conquista pelos obstáculos que teve que superar para alcançar seus objetivos. ~Booker T. Washington",
"Dificuldades reais podem ser superadas; são apenas as imaginárias que são invencíveis. ~Theodore N. Vail",
"É melhor falhar na originalidade do que ter sucesso na imitação. ~Herman Melville",
"A sorte fica do lado de quem ousa. ~Virgil",
"As pequenas mentes são domadas e subjugadas pelo infortúnio; mas as grandes mentes se elevam acima dele. ~Washington Irving",
"O fracasso é o condimento que dá sabor ao sucesso. ~Truman Capote",
"Não deixe que o que você não pode fazer interfira no que você pode fazer. ~John R. Wooden",
"Você pode ter que lutar uma batalha mais de uma vez para vencê-la. ~Margaret Thatcher",
"Fique com fome, fique tolo. ~Steve Jobs",
"Faça ou morra. ~Mahatama Gandhi",
"Conservar algo que possa recordar-te seria admitir que eu pudesse esquecer-te (Shakespeare)-= Codigos Das Carinhas =-",
"Amigo é aquele que sabe tudo a seu respeito, e, mesmo assim,ainda gosta de você (Kim Hubbard))-= Codigos Das Carinhas =-",
"Ninguém é igual a ninguém. Todo ser humano é um estranho ímpar (Carlos Drummond de Andrade)-= Codigos Das Carinhas =-", 
"Se você obedece a todas as regras, acaba perdendo toda a  diversão (Katherine Hepburn)-= Codigos Das Carinhas =-",
"O prazer dos grandes homens consiste em tornar os outros mais  felizes (Pascal)-= Codigos Das Carinhas =-",
"Só se vê bem com os olhos do coração. O essencial é invisível aos olhos (St. Exupéry)-= Codigos Das Carinhas =-",
"Quando um homem não encontra a si mesmo, não encontra a nada (Goethe)-= Codigos Das Carinhas =-",
"O homem de bem exige tudo de si próprio; o homem medíocre espera tudo dos outros (Confúcio)-= Codigos Das Carinhas =-",
"Sofrer e chorar significa viver (Dostoievski)-= Codigos Das Carinhas =-",
"Nada existe de mais fragil do que uma criatura iludida a seu próprio respeito (Torres Pastorinho)-= Codigos Das Carinhas =-",
"É no coração do homem que reside o princípio e o fim de todas as coisas (Tolstoi)-= Codigos Das Carinhas =-",
"A mentira é uma verdade que se esqueceu de acontecer (Mário Quintana)-= Codigos Das Carinhas =-",
"O amor é a asa veloz que Deus deu à alma para que ela voe até o céu (Michelângelo Buonarroti)-= Codigos Das Carinhas =-",
"Quanto menos inteligente um homem é, menos misteriosa lhe parece a existência (Arthur Schopenhauer)-= Codigos Das Carinhas =-",
"Onde há muito sentimento, a muita dor (Leonardo da Vinci)-= Codigos Das Carinhas =-",
"Quem não pode o que quer, queira o que pode (Leonardo da Vinci)-= Codigos Das Carinhas =-",
"O homem superior age antes de falar e depois age de acordo  com suas ações (Confúcio)-= Codigos Das Carinhas =-",
"A vida é a infância da imortalidade (Goethe)-= Codigos Das Carinhas =-",
"Quanto mais vigorosa a mente, mais violenta a paixão em que se  deixa envolver (Edmund Burke)-= Codigos Das Carinhas =-",
"Não concordo com uma só palavra do que dizeis, mas defenderei até a morte vosso direito de dizê-lo (Voltaire)-= Codigos Das Carinhas =-",
"Se você julga as pessoas, não tem tempo de amá-las (Mark Twain)-= Codigos Das Carinhas =-",
"Se a sua vida é isenta de fracassos, então você não está   assumindo os riscos necessários (H. Brown)-= Codigos Das Carinhas =-",
"O homem que venceu na vida é aquele que viveu bem, riu muitas vezes e amou muito (Robert Louis Stevenson)-= Codigos Das Carinhas =-", 
"Escolha um trabalho que você ame e não terás que trabalhar um  único dia em sua vida (Confúcio)-= Codigos Das Carinhas =-",
"O universo é uma harmonia de contrários (Pitágoras)-= Codigos Das Carinhas =-",
"A verdade é a melhor camuflagem. Ninguém acredita nela (Max Friesh)-= Codigos Das Carinhas =-",
"A televisão é a maior maravilha da ciência a serviço da imbecilidade humana (Barão de Itararé)-= Codigos Das Carinhas =-",
"Quase todos os homens são capazes de suportar adversidades, mas se quiser por à prova o caráter de um homem, dê-lhe poder (Abraham Lincoln)-= Codigos Das Carinhas =-",
"Muitas pessoas são bastante educadas para não falar com a boca cheia, porém não se preocupam em fazê-lo com a cabeça oca (Orson Welles)-= Codigos Das Carinhas =-",
"O inimigo mais perigoso que você poderá encontrar será sempre você mesmo (Nietzsche)-= Codigos Das Carinhas =-", 
"Por raro que seja um verdadeiro amor, é mais rara ainda a  verdadeira amizade (La Rochefoucauld)-= Codigos Das Carinhas =-",
"Solidão não é estar só, é estar entre 1000 pessoas e sentir falta de 1.-= Codigos Das Carinhas =-",
"Há pessoas que amam o poder, e outras que tem o poder de amar.-= Codigos Das Carinhas =-",
"Se você continua vivo é porque ainda não chegou aonde devia-= Codigos Das Carinhas =-"
"A vida é sofrer e se divertir. Por isso deve-se sempre estar à altura de qualquer sofrimento.-= Codigos Das Carinhas =-",
"As pessoas entram em nossa vida por acaso, mas não é por acaso que elas permanecem.-= Codigos Das Carinhas =-",
"Aqueles que sofreram muito são como quem aprendeu muitas línguas, compreendem a todos e se fazem compreender por todos.-= Codigos Das Carinhas =-",
"Toda decisão acertada é proveniente de experiência. E toda experiência é proveniente de uma decisão não acertada.-= Codigos Das Carinhas =-",
"Sempre dizem que o tempo muda as coisas, mas quem tem que mudá-las é você-= Codigos Das Carinhas =-",
"Quem ama sofre, quem sofre sente, quem sente luta, quem luta vence.-= Codigos Das Carinhas =-",
"Uma amizade não se compõe de abraços e sim de perdões e desabafos.-= Codigos Das Carinhas =-",
"Nunca me preocupo com o futuro, muito em breve ele virá. (Albert Einstein)-= Codigos Das Carinhas =-",
"No fim tudo dá certo, se ainda não deu certo é porque ainda não chegou ao fim.-= Codigos Das Carinhas =-",
"Neste mundo nada nos torna necessários, a não ser o amor. (Goethe)-= Codigos Das Carinhas =-",
"Os loucos são certos numa sociedade errada.-= Codigos Das Carinhas =-",
"O maior mistério do ser humano é tentar tirar da cabeça o que persiste no coração.-= Codigos Das Carinhas =-",
"Cada um pensa em mudar a humanidade, mas ninguém pensa em mudar a si mesmo.-= Codigos Das Carinhas =-",
"Atingir um objetivo que você não tem é tão difícil quanto voltar para um lugar que você nunca foi.-= Codigos Das Carinhas =-",
"Rir de tudo é coisa dos tontos, mas não rir de nada écoisa dos estupidos- Erasmo de Rotterdam-= Codigos Das Carinhas =-",
"A alegria está na luta, na tentativa, no sofrimentoenvolvido. Não na vitória propriamente dita. Mahatma Gandhi-= Codigos Das Carinhas =-",
"A vida não consiste em ter boas cartas na mão e sim em jogar bem as que se tem. Josh Billings-= Codigos Das Carinhas =-",
"Sempre tive pena de mim mesmo porque não tinha sapatos,até que encontrei um homem que não tinha pés.-= Codigos Das Carinhas =-",
"Os instantes mais dolorosos de nossa vida são aqueles que nos revelam à nós mesmos.-= Codigos Das Carinhas =-",
"O fato de querer que todos reconheçam a nossa generosidade a destrói imediatamente.-= Codigos Das Carinhas =-",
"Nenhuma certeza fatal é pior que a dúvida ameaçadora.-= Codigos Das Carinhas =-",
"A fé é a força da vida. Se o homem vive é porque acredita em alguma coisa.-= Codigos Das Carinhas =-",
"A felicidade não está no fim da jornada, e sim em cada curva do caminho que percorremos para encontrá-la.-= Codigos Das Carinhas =-",
"Se seus sonhos estiverem nas nuvens, não se preocupe,pois eles estão no lugar certo; agora construa os alicerses.-= Codigos Das Carinhas =-",
"Nossas dúvidas são traidoras e nos fazem perder o bem que às vezes poderíamos ganhar pelo medo de tentar.-= Codigos Das Carinhas =-",
"O que você fizer hoje é muito importante: porque você está trocando um dia da sua vida por isso.-= Codigos Das Carinhas =-",
"A maior covardia de um homem é depertar o amor de uma mulher sem ter a intenção de amá-la.-= Codigos Das Carinhas =-",
"Triste não é mudar de idéia. Triste é não ter idéia para mudar.-= Codigos Das Carinhas =-",
"É fácil apagar as pegadas; difícil, porém, é caminhar sem pisar o chão. Lao-Tsé-= Codigos Das Carinhas =-",
"Se nós não tivessemos defeitos, não teríamos tanto prazer em notá-los nos outros (La Rochefoucauld)-= Codigos Das Carinhas =-",
"O problema de resistir a uma tentação é que você pode não ter uma segunda chance (Lawrence Peter)-= Codigos Das Carinhas =-", 
"Grandes realizações são possíveis quando se dá importância aos pequenos começos (Lao Tzu)-= Codigos Das Carinhas =-",
"o MAL é a aucencia do amor... (ROQUEIRO INSANO)-= Codigos Das Carinhas"
];

var content = document.getElementById('content');
(function() {
	content.innerHTML= powerThoughts[Math.floor((Math.random() * 162) + 1)];
	var totalCount = 91;
    var num = Math.floor((Math.random() * totalCount) + 1);
    document.body.background = 'background/back' + num + '.jpg';
}());
